//===- emit.mlir - CSL dialect --emit-csl translation tests ---*- MLIR -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// Tests for air-translate --emit-csl: CSL dialect -> Cerebras CSL text files.
//
// Test 1: standalone csl.module -> <name>.csl
// Test 2: csl.spatial_placement -> layout.py + run.py + kernel.csl
//
//===----------------------------------------------------------------------===//

// ============================================================================
// Test 1: Standalone csl.module
//   Verifies: param, var, func, task, comptime, export_symbol
//
// RUN: air-translate --emit-csl --csl-output-dir=%t/t1 %s
// RUN: FileCheck %s --input-file=%t/t1/sender.csl --check-prefix=MOD
// ============================================================================

// MOD: // Auto-generated by air-translate --emit-csl
// MOD: param color_id: i32;
// MOD: var data: [128]f32;
// MOD: fn send() void {
// MOD: }
// MOD: task send_complete() color(1) {
// MOD: }
// MOD: comptime {
// MOD:   @export_symbol(data, "input")
// MOD:   @export_symbol(send, "run")
// MOD: }

csl.module @sender {
  csl.param @color_id : i32
  csl.var @data : memref<128xf32>

  csl.func @send() {
    csl.return
  }

  csl.task @send_complete() color(1) {
    csl.return
  }

  csl.comptime {
    csl.export_symbol @data alias("input")
    csl.export_symbol @send alias("run")
  }
}

// ============================================================================
// Test 2: Spatial placement -> layout.py + run.py + pe_program.csl
//   Verifies: Python SdkLayout API output, kernel .csl file, color/route/region
//             placement, paint, export_name; PE program: params, var, func, comptime
//
// RUN: air-translate --emit-csl --csl-output-dir=%t/t2 %s
// RUN: FileCheck %s --input-file=%t/t2/layout.py      --check-prefix=LAYOUT
// RUN: FileCheck %s --input-file=%t/t2/pe_program.csl --check-prefix=PE
// ============================================================================

// LAYOUT:      # Auto-generated by air-translate --emit-csl
// LAYOUT:      from cerebras.sdk.runtime.sdkruntimepybind import (
// LAYOUT:      layout = SdkLayout()
// LAYOUT:      color_{{[0-9]+}} = layout.alloc_color()
// LAYOUT:      rp_{{[0-9]+}} = RoutingPosition()
// LAYOUT:      rp_{{[0-9]+}}.set_input([Route.RAMP])
// LAYOUT:      rp_{{[0-9]+}}.set_output([Route.EAST])
// LAYOUT:      {{code[0-9]+}} = layout.create_code_region('./pe_program.csl',
// LAYOUT:      {{code[0-9]+}}.paint(IntVector(0, 0),
// LAYOUT:      {{code[0-9]+}}.place(0, 0)
// LAYOUT:      layout.export_name("arg_0", "[*]f32", mutable=True)
// LAYOUT:      layout.export_name("arg_1", "[*]f32", mutable=True)
// LAYOUT:      layout.export_name("init_and_compute", "fn()void")

// PE:      // Auto-generated by air-translate --emit-csl
// PE:      param memcpy_params: comptime_struct;
// PE:      const sys_mod = @import_module("<memcpy/memcpy>", memcpy_params)
// PE:      var arg_0: [1024]f32;
// PE:      var arg_1: [1024]f32;
// PE:      fn compute() void {
// PE:        const c_{{[0-9]+}}: i32 = 0;
// PE:        var v_{{[0-9]+}}: f32 =
// PE:      }
// PE:      fn init_and_compute() void {
// PE:      }
// PE:      comptime {
// PE:        @export_symbol(arg_0, "arg_0")
// PE:        @export_symbol(arg_1, "arg_1")
// PE:        @export_symbol(init_and_compute)
// PE:      }

// kernel
%k = csl.kernel "pe_program.csl" params({memcpy_params = 0 : i64}) {
  // Data in memory(can be own or borrowed memory from neighbor node.)
  csl.var @arg_0 : memref<1024xf32>
  csl.var @arg_1 : memref<1024xf32>

  // Function with arithmetic body (IsolatedFromAbove, uses local ops only)
  csl.func @compute() {
    %c0   = arith.constant 0 : i32
    %a    = arith.constant 1.5 : f32
    %b    = arith.constant 2.5 : f32
    %sum  = arith.addf %a, %b : f32
    csl.return
  }

  csl.func @init_and_compute() {
    csl.return
  }

  csl.comptime {
    csl.export_symbol @arg_0 alias("arg_0")
    csl.export_symbol @arg_1 alias("arg_1")
    csl.export_symbol @init_and_compute
  }
} : !csl.kernel

csl.spatial_placement {
  // resources for hardware, can assume infinite, compiler must be taking care of their allocation.
  %c = csl.color : !csl.color
  %r = csl.route in(RAMP) out(EAST) : i32
  %region = csl.code_region routes(%r) colors(%c) shape(2, 2) {
    csl.paint pe(0, 0) route(%r) color(%c)
  } : !csl.code_region

  csl.place %region at(0, 0) kernel(%k)

  csl.export_name "arg_0" : memref<1024xf32>
  csl.export_name "arg_1" : memref<1024xf32>
  csl.export_name "init_and_compute" : () -> ()
}
