//===- sdklayout5.mlir - SdkLayout Tutorial 5: GEMV ----------*- MLIR -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// MLIR model of the Cerebras SdkLayout Tutorial 5 (GEMV):
//   https://sdk.cerebras.net/csl/code-examples/tutorial-sdklayout-05-gemv
//
// A 4x4 matrix-vector multiply (GEMV: y = A*x) mapped to a 4x4 PE grid.
//
//   data_width  = 16       (width of the x input vector)
//   data_height = 32       (height of the A matrix / length of y output)
//   pe_width    = 4        (number of PE columns)
//   pe_height   = 4        (number of PE rows)
//   batch_width = 4        (x elements per PE column)
//   batch_height = 8       (A rows per PE row)
//   control_ep  = 40       (control endpoint color ID)
//
// Regions:
//   x_demux_adaptor (1x1)  — single PE that demuxes x data to x_demux strip
//   x_demux         (4x1)  — horizontal strip that fans x data to gemv PEs
//   b_demux_adaptor (1x1)  — single PE that demuxes b data to b_demux strip
//   b_demux         (1x4)  — vertical strip that fans b data to gemv PEs
//   gemv            (4x4)  — main compute region: y = A*x + b
//   y_mux           (1x4)  — collects y outputs from gemv PE rows
//
// Key features exercised (new in Tutorial 05):
//   - csl.routing_position with multiple output dirs: out("RAMP,SOUTH")
//   - csl.get_edge_routing for edge-specific routing overrides
//   - csl.paint_all with and without edge_routes
//   - csl.paint_range for rectangular sub-region painting
//   - csl.set_param_range_color — set_param_range(rect, color)
//   - csl.set_param_range_named — set_param_range(rect, 'name', color)
//   - csl.routing_position for variadic ports (multi-route)
//
// RUN: air-translate --emit-csl --csl-output-dir=%t %s
// RUN: FileCheck %s --input-file=%t/run.py --check-prefix=RUN_PY
//
//===----------------------------------------------------------------------===//

// ---- run.py checks ----
// RUN_PY: # Auto-generated by air-translate --emit-csl
// RUN_PY: layout = SdkLayout(platform)
//
// x_demux_adaptor region
// RUN_PY: x_demux_adaptor = layout.create_code_region('./demux_adaptor.csl', 'x_demux_adaptor', 1, 1)
//
// x_demux region with paint_all + get_edge_routing
// RUN_PY: x_demux = layout.create_code_region('./demux.csl', 'x_demux', 4, 1)
// RUN_PY: RoutingPosition().set_input([Route.NORTH]).set_output([Route.RAMP, Route.SOUTH])
// RUN_PY: get_edge_routing(Edge.RIGHT,
// RUN_PY: x_demux.paint_all(
//
// b_demux_adaptor region
// RUN_PY: b_demux_adaptor = layout.create_code_region('./demux_adaptor.csl', 'b_demux_adaptor', 1, 1)
//
// b_demux region with paint_all (no edge routes)
// RUN_PY: b_demux = layout.create_code_region('./demux.csl', 'b_demux', 1, 4)
// RUN_PY: b_demux.paint_all(
//
// gemv region with multi-direction routes
// RUN_PY: gemv = layout.create_code_region('./gemv.csl', 'gemv', 4, 4)
// RUN_PY: gemv.paint_all(x_in, [rp_{{[0-9]+}}], [er_{{[0-9]+}}])
// RUN_PY: gemv.paint_range(IntRectangle(IntVector(0, 0), IntVector(1, 4)), y_out, [rp_{{[0-9]+}}])
// RUN_PY: gemv.set_param_range(IntRectangle(IntVector(1, 0), IntVector(2, 4)), 'b_in', y_out)
//
// y_mux region with paint_all (no edge routes)
// RUN_PY: y_mux = layout.create_code_region('./mux.csl', 'y_mux', 1, 4)
// RUN_PY: y_mux.paint_all(
//
// layout.connect calls
// RUN_PY: layout.connect(
//
// Host stream
// RUN_PY: in_stream{{[0-9]+}} = layout.create_input_stream(
// RUN_PY: compile_artifacts = layout.compile(out_prefix='out')
// RUN_PY: print("SUCCESS!")

// ============================================================================
// Kernel stubs (minimal bodies — the focus of this test is the layout)
// ============================================================================

%k_demux_adaptor = csl.kernel "demux_adaptor.csl" {
  csl.param @batch_size : i16
  csl.param @x_color   : !csl.color
  csl.task @demux() color(8) {
    csl.return
  }
  csl.comptime {
  }
} : !csl.kernel

%k_demux = csl.kernel "demux.csl" {
  csl.param @batch_size : i16
  csl.param @in_color  : !csl.color
  csl.param @out_color : !csl.color
  csl.task @demux() color(8) {
    csl.return
  }
  csl.comptime {
  }
} : !csl.kernel

%k_gemv = csl.kernel "gemv.csl" {
  csl.param @batch_width  : i16
  csl.param @batch_height : i16
  csl.param @x_in    : !csl.color
  csl.param @b_in    : !csl.color
  csl.param @y_out   : !csl.color
  csl.var @result : memref<8xi16>
  csl.task @gemv() color(8) {
    csl.return
  }
  csl.comptime {
    csl.export_symbol @result
  }
} : !csl.kernel

%k_mux = csl.kernel "mux.csl" {
  csl.param @batch_size : i16
  csl.param @in_color  : !csl.color
  csl.param @out_color : !csl.color
  csl.task @mux() color(8) {
    csl.return
  }
  csl.comptime {
  }
} : !csl.kernel

// ============================================================================
// Spatial placement: GEMV 4x4 layout
// ============================================================================

csl.spatial_placement {

  // --- Colors ---
  //   x_in:  color for x data flowing INTO gemv PEs (from x_demux strip)
  //   b_in:  color for b data flowing INTO the right PE columns
  //   y_out: color for y data flowing OUT of gemv PEs (to y_mux strip)
  //   x_host: color for host-to-x_demux_adaptor stream
  %x_in  = csl.sym_color "x_in"  : !csl.color
  %b_in  = csl.sym_color "b_in"  : !csl.color
  %y_out = csl.sym_color "y_out" : !csl.color
  %x_host = csl.sym_color "x_host" : !csl.color

  // -------------------------------------------------------------------------
  // x_demux_adaptor (1x1) — receives x from host, forwards into x_demux strip
  // -------------------------------------------------------------------------
  %x_demux_adaptor = csl.code_region "x_demux_adaptor" routes() colors() shape(1, 1) {
  } : !csl.code_region
  csl.set_param_all %x_demux_adaptor param("batch_size") value(4 : i16)
  csl.set_param_color %x_demux_adaptor color(%x_host)
  csl.set_param_color %x_demux_adaptor color(%x_in)
  csl.place %x_demux_adaptor at(0, 0) kernel(%k_demux_adaptor)

  // -------------------------------------------------------------------------
  // x_demux (4x1) — horizontal strip: fans x data southward into gemv rows
  //   Interior PEs: input from NORTH, output to RAMP (PE) and SOUTH (next row)
  //   Right-edge PE: input from NORTH, output to RAMP only (no right neighbor)
  // -------------------------------------------------------------------------
  %x_demux = csl.code_region "x_demux" routes() colors() shape(4, 1) {
  } : !csl.code_region

  // Multi-direction route: x data arrives from NORTH, goes to both RAMP and SOUTH
  %rp_xd_core = csl.routing_position in("NORTH") out("RAMP,SOUTH") : i32

  // Right-edge override: x data arrives from NORTH, goes to RAMP only
  %rp_xd_edge = csl.routing_position in("NORTH") out("RAMP") : i32
  %er_xd_right = csl.get_edge_routing edge(RIGHT) routes(%rp_xd_edge) : i32

  csl.set_param_all %x_demux param("batch_size") value(4 : i16)
  csl.set_param_color %x_demux color(%x_in)
  csl.paint_all %x_demux color(%x_in) routes(%rp_xd_core) edge_routes(%er_xd_right)
  csl.place %x_demux at(0, 1) kernel(%k_demux)

  // -------------------------------------------------------------------------
  // b_demux_adaptor (1x1) — receives b from host, forwards into b_demux strip
  // -------------------------------------------------------------------------
  %b_demux_adaptor = csl.code_region "b_demux_adaptor" routes() colors() shape(1, 1) {
  } : !csl.code_region
  csl.set_param_all %b_demux_adaptor param("batch_size") value(4 : i16)
  csl.set_param_color %b_demux_adaptor color(%b_in)
  csl.place %b_demux_adaptor at(4, 2) kernel(%k_demux_adaptor)

  // -------------------------------------------------------------------------
  // b_demux (1x4) — vertical strip: fans b data eastward into gemv columns
  //   All PEs: input from WEST, output to RAMP and EAST
  //   (No edge override needed for 1-wide strip)
  // -------------------------------------------------------------------------
  %b_demux = csl.code_region "b_demux" routes() colors() shape(1, 4) {
  } : !csl.code_region

  // Single-direction routes for b_demux (no edge override needed)
  %rp_bd_core = csl.routing_position in("WEST") out("RAMP,EAST") : i32

  csl.set_param_all %b_demux param("batch_size") value(4 : i16)
  csl.set_param_color %b_demux color(%b_in)
  csl.paint_all %b_demux color(%b_in) routes(%rp_bd_core) edge_routes()
  csl.place %b_demux at(0, 2) kernel(%k_demux)

  // -------------------------------------------------------------------------
  // gemv (4x4) — main compute region
  //   - All PEs receive x_in (from x_demux strip above) and output y_out
  //   - Left column (x=0) also receives b_in from b_demux strip on the left
  //   - paint_all: configure x_in for all PEs
  //   - paint_range: configure y_out for left column (cols 0..1, all rows)
  //   - set_param_range_color: set x_in param on all PEs
  //   - set_param_range_named: set 'b_in' param on left column
  // -------------------------------------------------------------------------
  %gemv = csl.code_region "gemv" routes() colors() shape(4, 4) {
  } : !csl.code_region

  // x routing for gemv: all PEs receive x from NORTH (x_demux), output to RAMP
  %rp_gemv_x_core = csl.routing_position in("NORTH") out("RAMP") : i32
  // Edge override for bottom row: x arrives from NORTH, no SOUTH pass-through
  %rp_gemv_x_edge = csl.routing_position in("NORTH") out("RAMP") : i32
  %er_gemv_bottom = csl.get_edge_routing edge(BOTTOM) routes(%rp_gemv_x_edge) : i32

  // y routing for left PE column: y output goes WEST to y_mux
  %rp_gemv_y = csl.routing_position out("WEST") : i32

  csl.set_param_all %gemv param("batch_width")  value(4 : i16)
  csl.set_param_all %gemv param("batch_height") value(8 : i16)
  csl.set_param_color %gemv color(%x_in)
  csl.set_param_color %gemv color(%y_out)

  // paint_all: configure x_in routing for all PEs (with edge override for bottom)
  csl.paint_all %gemv color(%x_in) routes(%rp_gemv_x_core) edge_routes(%er_gemv_bottom)

  // paint_range: configure y_out routing for left column only (x=0..1, y=0..4)
  csl.paint_range %gemv rect(0, 0, 1, 4) color(%y_out) routes(%rp_gemv_y)

  // set_param_range_color: set x_in as a param on all left-column PEs
  csl.set_param_range_color %gemv rect(0, 0, 4, 4) color(%x_in)

  // set_param_range_named: set 'b_in' param (= y_out color) on left column
  csl.set_param_range_named %gemv rect(1, 0, 2, 4) param("b_in") color(%y_out)

  csl.place %gemv at(0, 2) kernel(%k_gemv)

  // -------------------------------------------------------------------------
  // y_mux (1x4) — collects y results from gemv left column
  //   All PEs: input from EAST (from gemv), output to RAMP (host)
  // -------------------------------------------------------------------------
  %y_mux = csl.code_region "y_mux" routes() colors() shape(1, 4) {
  } : !csl.code_region

  // y_mux routing: data comes from EAST (gemv), exits to RAMP (host)
  %rp_ymux = csl.routing_position in("EAST") out("RAMP") : i32

  csl.set_param_all %y_mux param("batch_size") value(8 : i16)
  csl.set_param_color %y_mux color(%y_out)
  // paint_all with no edge routes (uniform routing across all PEs)
  csl.paint_all %y_mux color(%y_out) routes(%rp_ymux) edge_routes()
  csl.place %y_mux at(5, 2) kernel(%k_mux)

  // -------------------------------------------------------------------------
  // Ports: x input from host, y output to host
  // -------------------------------------------------------------------------

  // x input port: host streams x data into the x_demux_adaptor from the left
  %rp_in = csl.routing_position in("RAMP") : i32
  %x_in_port = csl.input_port %x_demux_adaptor color(%x_host) edge(LEFT) routes(%rp_in) size(16) : !csl.port

  // y output port: y_mux delivers results to host on the right
  %rp_out = csl.routing_position out("RAMP") : i32
  %y_out_port = csl.output_port %y_mux color(%y_out) edge(RIGHT) routes(%rp_out) size(32) : !csl.port

  // -------------------------------------------------------------------------
  // Dataflow connections
  // -------------------------------------------------------------------------
  csl.dataflow %x_in_port -> %y_out_port

  // -------------------------------------------------------------------------
  // Host streams
  // -------------------------------------------------------------------------
  %x_stream = csl.input_stream %x_in_port : !csl.stream
}
