//===- sdklayout2.mlir - SdkLayout Tutorial 2: Routing --------*- MLIR -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// MLIR model of the Cerebras SdkLayout Tutorial 2 (Routing):
//   https://sdk.cerebras.net/csl/code-examples/tutorial-sdklayout-02-routing
//
// The tutorial creates a 2x1 grid with two PEs: sender (select=0) and
// receiver (select=1). A single shared send_receive.csl kernel is used.
// A symbolic color 'c' is declared globally and passed as a PE parameter.
// Routing: sender routes RAMP->EAST, receiver routes WEST->RAMP.
//
// This file models:
//   - send_receive.csl : csl.kernel with param select + param c (color),
//                        var buffer, tasks, comptime export
//   - spatial layout   : csl.sym_color, per-direction routes, 2x1 code region,
//                        per-PE set_param for 'select', set_param_color for 'c'
//
// RUN: air-translate --emit-csl --csl-output-dir=%t %s
// RUN: FileCheck %s --input-file=%t/send_receive.csl --check-prefix=CSL
// RUN: FileCheck %s --input-file=%t/run.py            --check-prefix=RUN_PY
//
//===----------------------------------------------------------------------===//

// ---- send_receive.csl checks ----
// CSL: // Auto-generated by air-translate --emit-csl
// CSL: param select: i16;
// CSL: param c: color;
// CSL: var buffer: [5]i16;
// CSL: comptime {
// CSL:   @export_symbol(buffer)
// CSL: }

// ---- run.py checks ----
// RUN_PY: # Auto-generated by air-translate --emit-csl
// RUN_PY: from cerebras.sdk.runtime.sdkruntimepybind import (
// RUN_PY: layout = SdkLayout(platform)
// RUN_PY: c = Color('c')
// RUN_PY: rp_{{[0-9]+}} = RoutingPosition()
// RUN_PY: rp_{{[0-9]+}}.set_input([Route.RAMP])
// RUN_PY: rp_{{[0-9]+}}.set_output([Route.EAST])
// RUN_PY: rp_{{[0-9]+}} = RoutingPosition()
// RUN_PY: rp_{{[0-9]+}}.set_input([Route.WEST])
// RUN_PY: rp_{{[0-9]+}}.set_output([Route.RAMP])
// RUN_PY: send_receive = layout.create_code_region('./send_receive.csl', 'send_receive', 2, 1)
// RUN_PY: send_receive.paint(IntVector(0, 0), c, [rp_{{[0-9]+}}])
// RUN_PY: send_receive.paint(IntVector(1, 0), c, [rp_{{[0-9]+}}])
// RUN_PY: send_receive.set_param(IntVector(0, 0), 'select', 0)
// RUN_PY: send_receive.set_param(IntVector(1, 0), 'select', 1)
// RUN_PY: send_receive.set_param_all(c)
// RUN_PY: send_receive.place(0, 0)
// RUN_PY: compile_artifacts = layout.compile(out_prefix='out')
// RUN_PY: runtime = SdkRuntime(compile_artifacts, platform, memcpy_required=False)
// RUN_PY: runtime.load()
// RUN_PY: runtime.run()
// RUN_PY: runtime.stop()
// RUN_PY: print("SUCCESS!")

// ============================================================================
// Kernel: send_receive.csl
//
// param select: u16;   (modeled as i16 in MLIR)
// param c: color;
// var buffer: [5]u16;  (modeled as i16 in MLIR)
// task send_task() — color bound at runtime via 'c'
// task receive_task() — color bound at runtime via 'c'
// task main() — startup task
//
// comptime { @export_symbol(buffer); }
// ============================================================================

%k = csl.kernel "send_receive.csl" {
  csl.param @select : i16
  csl.param @c : !csl.color
  csl.var @buffer : memref<5xi16>

  csl.task @send_task() color(8) {
    csl.return
  }

  csl.task @receive_task() color(9) {
    csl.return
  }

  csl.task @main() color(10) {
    csl.return
  }

  csl.comptime {
    csl.export_symbol @buffer
  }
} : !csl.kernel

// ============================================================================
// Spatial placement: run.py
//
// layout = SdkLayout(platform)
// c = Color('c')
// send_routes = RoutingPosition()
// send_routes.set_input([Route.RAMP])
// send_routes.set_output([Route.EAST])
// recv_routes = RoutingPosition()
// recv_routes.set_input([Route.WEST])
// recv_routes.set_output([Route.RAMP])
// send_receive = layout.create_code_region('./send_receive.csl', 'send_receive', 2, 1)
// send_receive.paint(IntVector(0, 0), c, [send_routes])
// send_receive.paint(IntVector(1, 0), c, [recv_routes])
// send_receive.set_param(IntVector(0, 0), 'select', 0)
// send_receive.set_param(IntVector(1, 0), 'select', 1)
// send_receive.set_param_all(c)
// send_receive.place(0, 0)
// ============================================================================

csl.spatial_placement {
  // Symbolic color 'c' — shared between sender and receiver PEs
  %c = csl.sym_color "c" : !csl.color

  // Routing: sender PE routes RAMP -> EAST (sends to neighbor)
  %send_routes = csl.route in(RAMP) out(EAST) : i32

  // Routing: receiver PE routes WEST -> RAMP (receives from neighbor)
  %recv_routes = csl.route in(WEST) out(RAMP) : i32

  // 2x1 code region: PE (0,0) = sender, PE (1,0) = receiver
  %region = csl.code_region "send_receive" routes(%send_routes, %recv_routes) colors(%c) shape(2, 1) {
    csl.paint pe(0, 0) route(%send_routes) color(%c)
    csl.paint pe(1, 0) route(%recv_routes) color(%c)
  } : !csl.code_region

  // Per-PE parameter: sender gets select=0, receiver gets select=1
  csl.set_param %region at(0, 0) param("select") value(0 : i16)
  csl.set_param %region at(1, 0) param("select") value(1 : i16)

  // Pass color object as parameter on all PEs
  csl.set_param_color %region color(%c)

  // Place the 2x1 region at grid origin (0, 0)
  csl.place %region at(0, 0) kernel(%k)
}
