//===- sdklayout4.mlir - SdkLayout Tutorial 4: H2D/D2H -------*- MLIR -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// MLIR model of the Cerebras SdkLayout Tutorial 4 (H2D/D2H streams):
//   https://sdk.cerebras.net/csl/code-examples/tutorial-sdklayout-04-h2d-d2h
//
// Single add2vec PE at (7, 4). Host sends two input vectors via H2D streams
// (rx1, rx2 colors), PE adds them, result returned via D2H stream (tx color).
//
// Key features modeled:
//   - csl.input_stream %port  : layout.create_input_stream(port)
//   - csl.output_stream %port : layout.create_output_stream(port)
//   - H2D/D2H stream placeholders in run.py runtime section
//
// RUN: air-translate --emit-csl --csl-output-dir=%t %s
// RUN: FileCheck %s --input-file=%t/run.py --check-prefix=RUN_PY
//
//===----------------------------------------------------------------------===//

// ---- run.py checks ----
// RUN_PY: # Auto-generated by air-translate --emit-csl
// RUN_PY: layout = SdkLayout(platform)
// RUN_PY: rp_{{[0-9]+}} = RoutingPosition()
// RUN_PY: rp_{{[0-9]+}}.set_input([Route.RAMP])
// RUN_PY: rp_{{[0-9]+}} = RoutingPosition()
// RUN_PY: rp_{{[0-9]+}}.set_output([Route.RAMP])
// RUN_PY: add2vec = layout.create_code_region('./add2vec.csl', 'add2vec', 1, 1)
// RUN_PY: rx1 = Color('rx1')
// RUN_PY: rx2 = Color('rx2')
// RUN_PY: tx = Color('tx')
// RUN_PY: add2vec.set_param_all('size', 10)
// RUN_PY: add2vec.set_param_all(rx1)
// RUN_PY: add2vec.set_param_all(rx2)
// RUN_PY: add2vec.set_param_all(tx)
// RUN_PY: port{{[0-9]+}} = add2vec.create_input_port(rx1, Edge.RIGHT,
// RUN_PY: port{{[0-9]+}} = add2vec.create_input_port(rx2, Edge.RIGHT,
// RUN_PY: port{{[0-9]+}} = add2vec.create_output_port(tx, Edge.LEFT,
// RUN_PY: add2vec.place(7, 4)
// RUN_PY: in_stream{{[0-9]+}} = layout.create_input_stream(
// RUN_PY: in_stream{{[0-9]+}} = layout.create_input_stream(
// RUN_PY: out_stream{{[0-9]+}} = layout.create_output_stream(
// RUN_PY: compile_artifacts = layout.compile(out_prefix='out')
// RUN_PY: runtime = SdkRuntime(
// RUN_PY: runtime.load()
// RUN_PY: runtime.run()
// RUN_PY: runtime.stop()
// RUN_PY: print("SUCCESS!")

// ============================================================================
// Kernel: add2vec.csl
// ============================================================================

%k_add2vec = csl.kernel "add2vec.csl" {
  csl.param @size : i16
  csl.param @rx1  : !csl.color
  csl.param @rx2  : !csl.color
  csl.param @tx   : !csl.color
  csl.var @result : memref<10xi16>
  csl.task @main() color(8) {
    csl.return
  }
  csl.comptime {
  }
} : !csl.kernel

// ============================================================================
// Spatial placement with H2D input streams and D2H output stream
// ============================================================================

csl.spatial_placement {
  // Routing: H2D input arrives from RAMP direction (host injects via fabric)
  %sender_routes   = csl.route in(RAMP) : i32
  // Routing: D2H output leaves to RAMP direction (host reads via fabric)
  %receiver_routes = csl.route out(RAMP) : i32

  // add2vec at (7, 4) — receives two vectors, adds them, sends result
  %add2vec = csl.code_region "add2vec" routes() colors() shape(1, 1) {
  } : !csl.code_region

  %rx1    = csl.sym_color "rx1" : !csl.color
  %rx2    = csl.sym_color "rx2" : !csl.color
  %a2v_tx = csl.sym_color "tx"  : !csl.color

  csl.set_param_all %add2vec param("size") value(10 : i16)
  csl.set_param_color %add2vec color(%rx1)
  csl.set_param_color %add2vec color(%rx2)
  csl.set_param_color %add2vec color(%a2v_tx)

  // Input ports for the two data vectors (host -> device)
  %rx1_port = csl.input_port  %add2vec color(%rx1)    edge(RIGHT) routes(%receiver_routes) size(10) : !csl.port
  %rx2_port = csl.input_port  %add2vec color(%rx2)    edge(RIGHT) routes(%receiver_routes) size(10) : !csl.port
  // Output port for the result vector (device -> host)
  %tx_port  = csl.output_port %add2vec color(%a2v_tx) edge(LEFT)  routes(%sender_routes)   size(10) : !csl.port

  csl.place %add2vec at(7, 4) kernel(%k_add2vec)

  // H2D streams: host sends data through these streams to the device
  %in_stream1 = csl.input_stream  %rx1_port : !csl.stream
  %in_stream2 = csl.input_stream  %rx2_port : !csl.stream
  // D2H stream: device sends result through this stream to the host
  %out_stream = csl.output_stream %tx_port  : !csl.stream
}
