//===- sdklayout3.mlir - SdkLayout Tutorial 3: Ports & Connections *- MLIR -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// MLIR model of the Cerebras SdkLayout Tutorial 3 (Ports and Connections):
//   https://sdk.cerebras.net/csl/code-examples/tutorial-sdklayout-03-ports-and-connections
//
// Four PEs communicate via named ports connected with layout.connect():
//   sender1 (2,2) -> add2vec (7,4)   via tx1_port -> rx1_port
//   sender2 (4,7) -> add2vec (7,4)   via tx2_port -> rx2_port
//   add2vec (7,4) -> receiver (3,3)  via tx_port  -> rx_port
//
// Key features modeled:
//   - csl.scoped_color %region "tx"   : region.color('tx')
//   - csl.sym_color "rx1"             : Color('rx1')
//   - csl.input_port / csl.output_port with edge and route
//   - csl.dataflow %src -> %dst       : layout.connect(src, dst)
//
// RUN: air-translate --emit-csl --csl-output-dir=%t %s
// RUN: FileCheck %s --input-file=%t/run.py --check-prefix=RUN_PY
//
//===----------------------------------------------------------------------===//

// ---- run.py checks ----
// RUN_PY: # Auto-generated by air-translate --emit-csl
// RUN_PY: layout = SdkLayout(platform)
// RUN_PY: rp_{{[0-9]+}} = RoutingPosition()
// RUN_PY: rp_{{[0-9]+}}.set_input([Route.RAMP])
// RUN_PY: rp_{{[0-9]+}} = RoutingPosition()
// RUN_PY: rp_{{[0-9]+}}.set_output([Route.RAMP])
// RUN_PY: sender1 = layout.create_code_region('./sender.csl', 'sender1', 1, 1)
// RUN_PY: sender1_tx = sender1.color('tx')
// RUN_PY: sender1.set_param_all('size', 10)
// RUN_PY: sender1.set_param_all(sender1_tx)
// RUN_PY: port{{[0-9]+}} = sender1.create_output_port(sender1_tx, Edge.RIGHT,
// RUN_PY: sender1.place(2, 2)
// RUN_PY: sender2 = layout.create_code_region('./sender.csl', 'sender2', 1, 1)
// RUN_PY: sender2_tx = sender2.color('tx')
// RUN_PY: sender2.set_param_all('size', 10)
// RUN_PY: sender2.set_param_all(sender2_tx)
// RUN_PY: port{{[0-9]+}} = sender2.create_output_port(sender2_tx, Edge.RIGHT,
// RUN_PY: sender2.place(4, 7)
// RUN_PY: add2vec = layout.create_code_region('./add2vec.csl', 'add2vec', 1, 1)
// RUN_PY: rx1 = Color('rx1')
// RUN_PY: rx2 = Color('rx2')
// RUN_PY: tx = Color('tx')
// RUN_PY: add2vec.set_param_all('size', 10)
// RUN_PY: add2vec.set_param_all(rx1)
// RUN_PY: add2vec.set_param_all(rx2)
// RUN_PY: add2vec.set_param_all(tx)
// RUN_PY: port{{[0-9]+}} = add2vec.create_input_port(rx1, Edge.RIGHT,
// RUN_PY: port{{[0-9]+}} = add2vec.create_input_port(rx2, Edge.RIGHT,
// RUN_PY: port{{[0-9]+}} = add2vec.create_output_port(tx, Edge.LEFT,
// RUN_PY: add2vec.place(7, 4)
// RUN_PY: receiver = layout.create_code_region('./receiver.csl', 'receiver', 1, 1)
// RUN_PY: rx = Color('rx')
// RUN_PY: receiver.set_param_all('size', 10)
// RUN_PY: receiver.set_param_all(rx)
// RUN_PY: port{{[0-9]+}} = receiver.create_input_port(rx, Edge.LEFT,
// RUN_PY: receiver.place(3, 3)
// RUN_PY: layout.connect(
// RUN_PY: layout.connect(
// RUN_PY: layout.connect(
// RUN_PY: compile_artifacts = layout.compile(out_prefix='out')
// RUN_PY: print("SUCCESS!")

// ============================================================================
// Kernel stubs (minimal bodies — the focus of this test is the layout)
// ============================================================================

%k_sender = csl.kernel "sender.csl" {
  csl.param @size : i16
  csl.param @tx : !csl.color
  csl.var @data : memref<10xi16>
  csl.task @main() color(8) {
    csl.return
  }
  csl.comptime {
    csl.export_symbol @data
  }
} : !csl.kernel

%k_receiver = csl.kernel "receiver.csl" {
  csl.param @size : i16
  csl.param @rx : !csl.color
  csl.var @result : memref<10xi16>
  csl.task @main() color(8) {
    csl.return
  }
  csl.comptime {
    csl.export_symbol @result
  }
} : !csl.kernel

%k_add2vec = csl.kernel "add2vec.csl" {
  csl.param @size : i16
  csl.param @rx1 : !csl.color
  csl.param @rx2 : !csl.color
  csl.param @tx : !csl.color
  csl.var @result : memref<10xi16>
  csl.task @main() color(8) {
    csl.return
  }
  csl.comptime {
    csl.export_symbol @result
  }
} : !csl.kernel

// ============================================================================
// Spatial placement: four regions connected via ports
// ============================================================================

csl.spatial_placement {
  // Shared routing configurations:
  //   sender_routes: input from RAMP (PE), output to right neighbor
  //   receiver_routes: input from left neighbor, output to RAMP (PE)
  %sender_routes   = csl.route in(RAMP) : i32
  %receiver_routes = csl.route out(RAMP) : i32

  // ---- sender1 at (2, 2) ----
  %sender1 = csl.code_region "sender1" routes() colors() shape(1, 1) {
  } : !csl.code_region
  %s1_tx = csl.scoped_color %sender1 "tx" : !csl.color
  csl.set_param_all %sender1 param("size") value(10 : i16)
  csl.set_param_color %sender1 color(%s1_tx)
  %tx1_port = csl.output_port %sender1 color(%s1_tx) edge(RIGHT) routes(%sender_routes) size(10) : !csl.port
  csl.place %sender1 at(2, 2) kernel(%k_sender)

  // ---- sender2 at (4, 7) ----
  %sender2 = csl.code_region "sender2" routes() colors() shape(1, 1) {
  } : !csl.code_region
  %s2_tx = csl.scoped_color %sender2 "tx" : !csl.color
  csl.set_param_all %sender2 param("size") value(10 : i16)
  csl.set_param_color %sender2 color(%s2_tx)
  %tx2_port = csl.output_port %sender2 color(%s2_tx) edge(RIGHT) routes(%sender_routes) size(10) : !csl.port
  csl.place %sender2 at(4, 7) kernel(%k_sender)

  // ---- add2vec at (7, 4) ----
  %add2vec = csl.code_region "add2vec" routes() colors() shape(1, 1) {
  } : !csl.code_region
  %rx1     = csl.sym_color "rx1" : !csl.color
  %rx2     = csl.sym_color "rx2" : !csl.color
  %a2v_tx  = csl.sym_color "tx"  : !csl.color
  csl.set_param_all %add2vec param("size") value(10 : i16)
  csl.set_param_color %add2vec color(%rx1)
  csl.set_param_color %add2vec color(%rx2)
  csl.set_param_color %add2vec color(%a2v_tx)
  %rx1_port = csl.input_port  %add2vec color(%rx1)   edge(RIGHT) routes(%receiver_routes) size(10) : !csl.port
  %rx2_port = csl.input_port  %add2vec color(%rx2)   edge(RIGHT) routes(%receiver_routes) size(10) : !csl.port
  %tx_port  = csl.output_port %add2vec color(%a2v_tx) edge(LEFT) routes(%sender_routes)   size(10) : !csl.port
  csl.place %add2vec at(7, 4) kernel(%k_add2vec)

  // ---- receiver at (3, 3) ----
  %receiver = csl.code_region "receiver" routes() colors() shape(1, 1) {
  } : !csl.code_region
  %rx = csl.sym_color "rx" : !csl.color
  csl.set_param_all %receiver param("size") value(10 : i16)
  csl.set_param_color %receiver color(%rx)
  %rx_port = csl.input_port %receiver color(%rx) edge(LEFT) routes(%receiver_routes) size(10) : !csl.port
  csl.place %receiver at(3, 3) kernel(%k_receiver)

  // ---- Dataflow connections ----
  csl.dataflow %tx1_port -> %rx1_port
  csl.dataflow %tx2_port -> %rx2_port
  csl.dataflow %tx_port  -> %rx_port
}
