//===- sdklayout1.mlir - SdkLayout Tutorial 1: Introduction ---*- MLIR -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// MLIR model of the Cerebras SdkLayout Tutorial 1 (Introduction):
//   https://sdk.cerebras.net/csl/code-examples/tutorial-sdklayout-01-introduction
//
// The tutorial compiles a 1x1 PE program (gv.csl) that accepts an i16
// parameter from the host, assigns it to an exported variable via a local
// task, and verifies the result on the host using SdkRuntime.
//
// This file models:
//   - gv.csl  : csl.kernel with param, var, task, comptime
//   - layout  : csl.spatial_placement with create_code_region + set_param_all
//
// RUN: air-translate --emit-csl --csl-output-dir=%t %s
// RUN: FileCheck %s --input-file=%t/gv.csl       --check-prefix=GV
// RUN: FileCheck %s --input-file=%t/layout.py    --check-prefix=LAYOUT
// RUN: FileCheck %s --input-file=%t/run.py       --check-prefix=RUN_PY
//
//===----------------------------------------------------------------------===//

// ---- gv.csl checks ----
// GV: // Auto-generated by air-translate --emit-csl
// GV: param value: i16;
// GV: var gv: i16;
// GV: task main() color(8) {
// GV: }
// GV: comptime {
// GV:   @export_symbol(gv)
// GV: }

// ---- layout.py checks ----
// LAYOUT: # Auto-generated by air-translate --emit-csl
// LAYOUT: from cerebras.sdk.runtime.sdkruntimepybind import (
// LAYOUT: layout = SdkLayout()
// LAYOUT: {{code[0-9]+}} = layout.create_code_region('./gv.csl',
// LAYOUT: {{code[0-9]+}}.place(0, 0)
// LAYOUT: {{code[0-9]+}}.set_param_all('value', 550)

// ---- run.py checks ----
// RUN_PY: # Auto-generated by air-translate --emit-csl
// RUN_PY: from cerebras.sdk.runtime.sdkruntimepybind import (
// RUN_PY: value = 550
// RUN_PY: layout = SdkLayout(platform)
// RUN_PY: {{code[0-9]+}} = layout.create_code_region('./gv.csl',
// RUN_PY: {{code[0-9]+}}.set_param_all('value', 550)
// RUN_PY: compile_artifacts = layout.compile(out_prefix='out')
// RUN_PY: runtime = SdkRuntime(compile_artifacts, platform, memcpy_required=False)
// RUN_PY: runtime.load()
// RUN_PY: runtime.run()
// RUN_PY: runtime.stop()
// RUN_PY: result_gv = runtime.read_symbol(0, 0, 'gv', dtype='uint16')
// RUN_PY: print("SUCCESS!")

// ============================================================================
// Kernel: gv.csl
//
// param value: i16;
// export var gv: i16;
//
// const main_id = @get_local_task_id(8);
// task main() void { gv = value; }
//
// comptime {
//   @bind_local_task(main, main_id);
//   @activate(main_id);
// }
// ============================================================================

%k = csl.kernel "gv.csl" {
  // param value: i16;
  csl.param @value : i16

  // export var gv: i16;
  csl.var @gv : i16

  // task main() — local task bound to id 8 via @bind_local_task in comptime.
  // Modeled as color(8) since local task IDs share the color ID space.
  csl.task @main() color(8) {
    // gv = value;  (assignment not yet modeled as MLIR ops)
    csl.return
  }

  csl.comptime {
    // @bind_local_task(main, main_id) and @activate(main_id) are implied.
    csl.export_symbol @gv
  }
} : !csl.kernel

// ============================================================================
// Spatial placement: layout.py
//
// layout = SdkLayout(platform)
// code = layout.create_code_region('./gv.csl', 'gv', 1, 1)
// code.set_param_all('value', 550)
// compile_artifacts = layout.compile(out_prefix='out')
//
// Runtime (host-side Python, not modeled in CSL dialect):
//   runtime = SdkRuntime(compile_artifacts, platform, memcpy_required=False)
//   runtime.load(); runtime.run(); runtime.stop()
//   result = runtime.read_symbol(0, 0, 'gv', dtype='uint16')
//   assert result == [550]
// ============================================================================

csl.spatial_placement {
  // 1x1 code region — no routing/colors needed for this tutorial
  %region = csl.code_region routes() colors() shape(1, 1) {
  } : !csl.code_region

  csl.place %region at(0, 0) kernel(%k)

  // code.set_param_all('value', 550)
  csl.set_param_all %region param("value") value(550 : i16)
}
