//===- CSLHostEmitter.cpp - Emit host run.py -------------------*- C++ -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// Registers --emit-csl-host. Walks csl.wafer > csl.host and emits the Python
// SdkRuntime host driver.
//
//===----------------------------------------------------------------------===//

#include "CSLEmitCommon.h"

#include "air/Dialect/CSL/CSLDialect.h"
#include "air/Dialect/CSL/CSLHostOps.h"
#include "air/Dialect/CSL/CSLLayoutOps.h"
#include "air/Dialect/CSL/CSLOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/raw_ostream.h"

#include <string>

using namespace mlir;

namespace xilinx {
namespace csl {

namespace {

class HostEmitter {
public:
  explicit HostEmitter(llvm::raw_ostream &os) : os(os) {}
  LogicalResult emit(ModuleOp module);

private:
  llvm::raw_ostream &os;
};

LogicalResult HostEmitter::emit(ModuleOp module) {
  namespace cslns = xilinx::csl;
  namespace hostns = xilinx::csl_host;

  cslns::WaferOp wafer;
  module.walk([&](cslns::WaferOp w) { wafer = w; });
  if (!wafer) {
    os << "# No csl.wafer found in module.\n";
    return success();
  }

  cslns::HostOp host;
  for (Operation &op : wafer.getBody().front()) {
    if (auto h = dyn_cast<cslns::HostOp>(&op)) {
      host = h;
      break;
    }
  }
  if (!host) {
    os << "# No csl.host found in csl.wafer.\n";
    return success();
  }

  // Collect block arg names from csl.host region
  llvm::SmallVector<std::string, 4> argNames;
  llvm::SmallVector<Type, 4> argTypes;
  if (!host.getBody().empty()) {
    Block &entry = host.getBody().front();
    for (BlockArgument arg : entry.getArguments()) {
      argNames.push_back("arg" + std::to_string(arg.getArgNumber()));
      argTypes.push_back(arg.getType());
    }
  }

  // Determine N from the first memref arg
  int64_t N = -1;
  for (Type t : argTypes) {
    if (auto memTy = dyn_cast<MemRefType>(t)) {
      if (memTy.getRank() >= 1 && memTy.getDimSize(0) > 0) {
        N = memTy.getDimSize(0);
        break;
      }
    }
  }

  std::string sig = "target";
  for (auto &name : argNames)
    sig += ", " + name;

  os << "# Generated by air-translate --emit-csl-host\n\n";
  os << "from csl_layout import get_layout\n";
  os << "from cerebras.sdk.client import SdkRuntime\n";
  os << "import numpy as np\n\n";

  os << "def main(" << sig << "):\n";
  os << "    artifacts = get_layout(target).compile(\"out/\")\n";
  if (N > 0)
    os << "    N = " << N << "\n";
  os << "    with SdkRuntime(artifacts) as runner:\n";

  if (!host.getBody().empty()) {
    Block &entry = host.getBody().front();
    for (Operation &op : entry) {
      // csl_host.memcpy_h2d
      if (auto h2dOp = dyn_cast<hostns::MemcpyH2DOp>(&op)) {
        SymbolRefAttr symAttr = h2dOp.getSym();
        StringRef leafSym;
        if (!symAttr.getNestedReferences().empty())
          leafSym = symAttr.getNestedReferences().back().getValue();
        else
          leafSym = symAttr.getRootReference().getValue();

        Value src = h2dOp.getSrc();
        std::string srcName = "?";
        if (auto barg = dyn_cast<BlockArgument>(src))
          srcName = argNames[barg.getArgNumber()];

        int64_t px = h2dOp.getPx();
        int64_t py = h2dOp.getPy();
        int64_t w = h2dOp.getWidth();
        int64_t h = h2dOp.getHeight();
        std::string nStr = (N > 0) ? "N" : "len(" + srcName + ")";

        os << "        runner.memcpy_h2d(runner.get_id(\"" << leafSym
           << "\"), " << srcName << ", " << px << ", " << py << ", " << w
           << ", " << h << ", " << nStr << ")\n";
        continue;
      }

      // csl_host.memcpy_d2h
      if (auto d2hOp = dyn_cast<hostns::MemcpyD2HOp>(&op)) {
        SymbolRefAttr symAttr = d2hOp.getSym();
        StringRef leafSym;
        if (!symAttr.getNestedReferences().empty())
          leafSym = symAttr.getNestedReferences().back().getValue();
        else
          leafSym = symAttr.getRootReference().getValue();

        Value dst = d2hOp.getDst();
        std::string dstName = "?";
        if (auto barg = dyn_cast<BlockArgument>(dst))
          dstName = argNames[barg.getArgNumber()];

        int64_t px = d2hOp.getPx();
        int64_t py = d2hOp.getPy();
        int64_t w = d2hOp.getWidth();
        int64_t h = d2hOp.getHeight();
        std::string nStr = (N > 0) ? "N" : "len(" + dstName + ")";

        os << "        runner.memcpy_d2h(" << dstName
           << ", runner.get_id(\"" << leafSym << "\"), " << px << ", " << py
           << ", " << w << ", " << h << ", " << nStr << ")\n";
        continue;
      }

      // csl_host.launch
      if (auto launchOp = dyn_cast<hostns::LaunchOp>(&op)) {
        SymbolRefAttr symAttr = launchOp.getSym();
        StringRef leafSym;
        if (!symAttr.getNestedReferences().empty())
          leafSym = symAttr.getNestedReferences().back().getValue();
        else
          leafSym = symAttr.getRootReference().getValue();

        os << "        runner.launch(\"" << leafSym
           << "\", nonblock=False)\n";
        continue;
      }
    }
  }

  return success();
}

} // namespace

LogicalResult runHostEmitter(ModuleOp module, llvm::raw_ostream &os) {
  HostEmitter emitter(os);
  return emitter.emit(module);
}

void registerCSLHostTranslation() {
  static TranslateFromMLIRRegistration reg(
      "emit-csl-host",
      "Emit CSL v2 host runtime Python (run.py) from csl.host",
      [](ModuleOp module, llvm::raw_ostream &os) -> LogicalResult {
        return runHostEmitter(module, os);
      },
      [](DialectRegistry &registry) {
        registry.insert<xilinx::csl::CSLDialect,
                        xilinx::csl_layout::CSLLayoutDialect,
                        xilinx::csl_host::CSLHostDialect,
                        mlir::arith::ArithDialect,
                        mlir::func::FuncDialect,
                        mlir::memref::MemRefDialect,
                        mlir::scf::SCFDialect>();
      });
}

} // namespace csl
} // namespace xilinx
