//===- CSLLayoutEmitter.cpp - Emit csl_layout.py ---------------*- C++ -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// Registers --emit-csl-layout. Walks csl.wafer > csl.layout and emits the
// Python SdkLayout script that the host uses to compile the CSL program.
//
//===----------------------------------------------------------------------===//

#include "CSLEmitCommon.h"

#include "air/Dialect/CSL/CSLDialect.h"
#include "air/Dialect/CSL/CSLHostOps.h"
#include "air/Dialect/CSL/CSLLayoutOps.h"
#include "air/Dialect/CSL/CSLOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/raw_ostream.h"

#include <string>

using namespace mlir;

namespace xilinx {
namespace csl {

namespace {

class LayoutEmitter {
public:
  explicit LayoutEmitter(llvm::raw_ostream &os) : os(os) {}
  LogicalResult emit(xilinx::csl::WaferOp wafer);

private:
  llvm::raw_ostream &os;
};

LogicalResult LayoutEmitter::emit(xilinx::csl::WaferOp wafer) {
  namespace cslns = xilinx::csl;
  namespace layoutns = xilinx::csl_layout;

  // Find csl.layout
  cslns::LayoutOp layout;
  for (Operation &op : wafer.getBody().front()) {
    if (auto l = dyn_cast<cslns::LayoutOp>(&op)) {
      layout = l;
      break;
    }
  }
  if (!layout) {
    os << "# No csl.layout found in csl.wafer.\n";
    return success();
  }

  // Find the first csl.program to get the program name
  std::string progName = "pe_program";
  for (Operation &op : wafer.getBody().front()) {
    if (auto prog = dyn_cast<cslns::ProgramOp>(&op)) {
      progName = prog.getSymName().str();
      break;
    }
  }

  // Collect place ops to determine grid dimensions
  int64_t maxX = 0, maxY = 0;
  bool hasPlace = false;

  struct ParamBinding {
    std::string name;
    int64_t value;
  };
  llvm::SmallVector<ParamBinding, 4> params;

  layout.getBody().walk([&](layoutns::PlaceOp placeOp) {
    int64_t px = placeOp.getPx();
    int64_t py = placeOp.getPy();
    if (px > maxX) maxX = px;
    if (py > maxY) maxY = py;
    hasPlace = true;

    for (NamedAttribute attr : placeOp->getAttrs()) {
      StringRef name = attr.getName().getValue();
      if (name == "prog" || name == "px" || name == "py")
        continue;
      if (auto intAttr = dyn_cast<IntegerAttr>(attr.getValue()))
        params.push_back({name.str(), intAttr.getInt()});
    }
  });

  int64_t W = hasPlace ? maxX + 1 : 1;
  int64_t H = hasPlace ? maxY + 1 : 1;

  os << "# Generated by air-translate --emit-csl-layout\n\n";
  os << "from cerebras.sdk.runtime.sdkruntimepybind import SdkLayout, SdkTarget\n\n";
  os << "def get_layout(target: SdkTarget) -> SdkLayout:\n";
  os << "    layout = SdkLayout(target)\n";
  os << "    region = layout.create_code_region(\"" << progName << ".csl\", \""
     << progName << "\", " << W << ", " << H << ")\n";

  for (auto &p : params)
    os << "    region.set_param_all(\"" << p.name << "\", " << p.value << ")\n";

  os << "    region.place(0, 0)\n";
  os << "    return layout\n";

  return success();
}

} // namespace

// Wafer-scoped entry point used by CSLEmitAll.cpp.
LogicalResult runLayoutEmitter(xilinx::csl::WaferOp wafer,
                               llvm::raw_ostream &os) {
  LayoutEmitter emitter(os);
  return emitter.emit(wafer);
}

// Module-scoped entry point for backward compatibility (--emit-csl-layout).
LogicalResult runLayoutEmitter(ModuleOp module, llvm::raw_ostream &os) {
  namespace cslns = xilinx::csl;
  llvm::SmallVector<cslns::WaferOp, 4> wafers;
  module.walk([&](cslns::WaferOp w) { wafers.push_back(w); });
  if (wafers.empty()) {
    os << "# No csl.wafer found in module.\n";
    return success();
  }
  if (wafers.size() > 1)
    os << "# note: " << wafers.size()
       << " wafers in module; emitting " << wafers[0].getSymName() << "\n";
  return runLayoutEmitter(wafers[0], os);
}

void registerCSLLayoutTranslation() {
  static TranslateFromMLIRRegistration reg(
      "emit-csl-layout",
      "Emit CSL v2 layout Python (csl_layout.py) from csl.layout",
      [](ModuleOp module, llvm::raw_ostream &os) -> LogicalResult {
        return runLayoutEmitter(module, os);
      },
      [](DialectRegistry &registry) {
        registry.insert<xilinx::csl::CSLDialect,
                        xilinx::csl_layout::CSLLayoutDialect,
                        xilinx::csl_host::CSLHostDialect,
                        mlir::arith::ArithDialect,
                        mlir::func::FuncDialect,
                        mlir::memref::MemRefDialect,
                        mlir::scf::SCFDialect>();
      });
}

} // namespace csl
} // namespace xilinx
