//===- CSLProgramEmitter.cpp - Emit PE program.csl -------------*- C++ -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// Registers --emit-csl-program. Walks csl.wafer > csl.program and emits the
// PE-level CSL source text.
//
//===----------------------------------------------------------------------===//

#include "CSLEmitCommon.h"

#include "air/Dialect/CSL/CSLDialect.h"
#include "air/Dialect/CSL/CSLHostOps.h"
#include "air/Dialect/CSL/CSLLayoutOps.h"
#include "air/Dialect/CSL/CSLOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/raw_ostream.h"

#include <string>

using namespace mlir;
using xilinx::csl::detail::cslTypeName;
using xilinx::csl::detail::emitFuncBody;

namespace xilinx {
namespace csl {

namespace {

class ProgramEmitter {
public:
  explicit ProgramEmitter(llvm::raw_ostream &os) : os(os) {}
  LogicalResult emit(xilinx::csl::WaferOp wafer);
  LogicalResult emitProgram(xilinx::csl::ProgramOp prog);

private:
  llvm::raw_ostream &os;
};

LogicalResult ProgramEmitter::emit(xilinx::csl::WaferOp wafer) {
  namespace cslns = xilinx::csl;

  // Find the first csl.program
  cslns::ProgramOp prog;
  wafer.walk([&](cslns::ProgramOp p) {
    if (!prog) prog = p;
  });
  if (!prog) {
    os << "// No csl.program found in csl.wafer.\n";
    return success();
  }

  return emitProgram(prog);
}

LogicalResult ProgramEmitter::emitProgram(xilinx::csl::ProgramOp prog) {
  namespace cslns = xilinx::csl;

  os << "// Generated by air-translate --emit-csl-program\n\n";

  // Emit memcpy module preamble (required for SDK host communication).
  os << "param memcpy_params: comptime_struct;\n";
  os << "const sys_mod = @import_module(\"<memcpy/memcpy>\", memcpy_params);\n\n";

  // Layout library for runtime PE coord access (get_x_coord / get_y_coord).
  os << "const layout_mod = @import_module(\"<layout>\");\n\n";

  // Re-declare every csl.color from the parent wafer's csl.layout at PE
  // scope. cslc compiles each PE source independently and needs to resolve
  // any `fabric_color = @<sym>` or `@bind_local_task(.., @<sym>)` references.
  // We mirror layout's `const <sym> = @get_color(N);` declarations here.
  if (auto wafer = prog->getParentOfType<cslns::WaferOp>()) {
    bool anyColor = false;
    wafer.walk([&](cslns::ColorOp c) {
      auto idAttr = c.getIdAttr();
      if (!idAttr)
        return;
      os << "const " << c.getSymName() << ": color = @get_color("
         << idAttr.getInt() << ");\n";
      anyColor = true;
    });
    if (anyColor)
      os << "\n";
  }

  // WSE-3 fabric DSDs (fabin/fabout) require an `.input_queue` or
  // `.output_queue` field. Walk the program for csl.get_fab_dsd ops and
  // declare a unique input/output queue for each at PE file scope.
  //
  // Queue IDs start at 2: ids 0 and 1 are reserved by the memcpy
  // infrastructure for the cmd_stream and h2d/d2h plumbing on WSE-3 — using
  // them for user-visible fabric DSDs causes silent kernel stalls (the d2h
  // returns 0 bytes).
  //
  // The queue name follows `<color>_<dir>_q` so the body emitter (which
  // emits the .input_queue/.output_queue field) can reference it
  // deterministically. Skipped when the wafer is not WSE-3.
  bool isWse3 = false;
  if (auto wafer = prog->getParentOfType<cslns::WaferOp>()) {
    if (auto archAttr = wafer->getAttrOfType<StringAttr>("arch"))
      isWse3 = archAttr.getValue() == "wse3";
  }
  if (isWse3) {
    unsigned outQId = 2; // 0 and 1 reserved by memcpy internals on WSE-3
    unsigned inQId = 2;
    bool anyQ = false;
    prog.walk([&](cslns::GetFabDsdOp fab) {
      StringRef dirStr =
          ::xilinx::csl::stringifyFabDsdDirection(fab.getDirection());
      std::string colorName = fab.getColor().str();
      if (dirStr == "fabout") {
        os << "const " << colorName << "_out_q: output_queue = "
           << "@get_output_queue(" << outQId++ << ");\n";
      } else {
        os << "const " << colorName << "_in_q: input_queue = "
           << "@get_input_queue(" << inQId++ << ");\n";
      }
      anyQ = true;
    });
    if (anyQ)
      os << "\n";
  }

  // Build outer map early — user-level csl.import_module results go here so
  // that csl.builtin_call "name" in %mod (...) can resolve the module name.
  llvm::DenseMap<Value, std::string> outerMap;

  // 0.5 Emit user-level csl.import_module ops at program scope, in IR order.
  //     Path may be anything (e.g. "<math>", "<memcpy/get_params>"). An
  //     optional params dict emits as a CSL anonymous struct literal.
  {
    unsigned modCount = 0;
    for (Operation &op : prog.getBody().front()) {
      auto imp = dyn_cast<cslns::ImportModuleOp>(&op);
      if (!imp) continue;
      std::string name = "mod" + std::to_string(modCount++);
      outerMap[imp.getResult()] = name;
      os << "const " << name << " = @import_module(\""
         << imp.getModuleName() << "\"";
      if (auto params = imp.getParamsAttr()) {
        os << ", .{ ";
        bool first = true;
        for (NamedAttribute kv : params) {
          if (!first) os << ", ";
          first = false;
          os << "." << kv.getName().getValue() << " = ";
          // Support integer and string values for now; scalar/dict nesting
          // can be added later when a kernel needs it.
          if (auto ia = dyn_cast<IntegerAttr>(kv.getValue())) {
            os << ia.getInt();
          } else if (auto sa = dyn_cast<StringAttr>(kv.getValue())) {
            os << "\"" << sa.getValue() << "\"";
          } else {
            // Fall back to MLIR's attribute printer.
            kv.getValue().print(os);
          }
        }
        os << " }";
      }
      os << ");\n";
    }
    if (modCount > 0)
      os << "\n";
  }

  // 1. Emit param declarations from block args with !csl.comptime<T> type.
  Region &progBody = prog.getBody();
  if (!progBody.empty()) {
    Block &entryBlock = progBody.front();
    for (BlockArgument arg : entryBlock.getArguments()) {
      Type t = arg.getType();
      if (auto comptime = mlir::dyn_cast<cslns::ComptimeType>(t)) {
        std::string argName = "arg" + std::to_string(arg.getArgNumber());
        os << "param " << argName << ": " << cslTypeName(comptime.getInnerType())
           << ";\n";
      }
    }
    os << "\n";
  }

  // 2. Emit var declarations
  bool hasVars = false;
  for (Operation &op : prog.getBody().front()) {
    if (auto varOp = dyn_cast<cslns::VarOp>(&op)) {
      auto memTy = dyn_cast<MemRefType>(varOp.getResult().getType());
      if (!memTy || memTy.getRank() != 1) {
        varOp.emitOpError("CSLEmit: csl.var must have 1-D memref type");
        return failure();
      }
      std::string eltName = cslTypeName(memTy.getElementType());
      int64_t dim = memTy.getDimSize(0);
      os << "var " << varOp.getSymName() << ": [" << dim << "]" << eltName
         << ";\n";
      outerMap[varOp.getResult()] = varOp.getSymName().str();
      hasVars = true;
    }
  }
  if (hasVars)
    os << "\n";

  // Emit pointer variables for exported buffers (SDK memcpy requirement).
  // Direction determines mutability: "in" → var (host writes), "out" → const (host reads).
  bool hasPointers = false;
  for (Operation &op : prog.getBody().front()) {
    if (auto expOp = dyn_cast<cslns::ExportOp>(&op)) {
      auto kind = expOp.getKind();
      if (kind.has_value() && *kind == "func")
        continue; // function exports don't need pointers

      auto dir = expOp.getDirection();
      if (dir.has_value() && *dir == "internal")
        continue;

      StringRef sym = expOp.getSym();

      // Find the var op to get element type
      std::string eltName = "f32"; // default
      for (Operation &varOp : prog.getBody().front()) {
        if (auto v = dyn_cast<cslns::VarOp>(&varOp)) {
          if (v.getSymName() == sym) {
            if (auto memTy = dyn_cast<MemRefType>(v.getResult().getType()))
              eltName = cslTypeName(memTy.getElementType());
            break;
          }
        }
      }

      bool isOutput = dir.has_value() && *dir == "out";
      os << (isOutput ? "const " : "var ") << sym << "_ptr: [*]" << eltName
         << " = &" << sym << ";\n";
      hasPointers = true;
    }
  }
  if (hasPointers)
    os << "\n";

  // 2.5 Emit func.func private helpers before csl.func.
  for (Operation &op : prog.getBody().front()) {
    auto fOp = dyn_cast<func::FuncOp>(&op);
    if (!fOp || !fOp.isPrivate()) continue;

    os << "fn " << fOp.getSymName() << "(";
    llvm::DenseMap<Value, std::string> helperMap = outerMap;
    for (auto it : llvm::enumerate(fOp.getArguments())) {
      if (it.index()) os << ", ";
      std::string argName = "a" + std::to_string(it.index());
      helperMap[it.value()] = argName;
      os << argName << ": " << cslTypeName(it.value().getType());
    }
    os << ") ";
    if (fOp.getNumResults() > 0)
      os << cslTypeName(fOp.getResultTypes()[0]) << " ";
    else
      os << "void ";
    os << "{\n";
    unsigned helperTemp = 0;
    if (failed(emitFuncBody(fOp.getBody(), os, /*indentLevel=*/1,
                            outerMap, helperMap, helperTemp)))
      return failure();
    os << "}\n\n";
  }

  // 3. Emit function definitions
  for (Operation &op : prog.getBody().front()) {
    auto funcOp = dyn_cast<cslns::FuncOp>(&op);
    if (!funcOp) continue;

    os << "fn " << funcOp.getSymName() << "() void {\n";

    llvm::DenseMap<Value, std::string> nameMap;
    for (auto &kv : outerMap)
      nameMap[kv.first] = kv.second;

    unsigned tempCount = 0;
    if (failed(emitFuncBody(funcOp.getBody(), os, /*indentLevel=*/1,
                            outerMap, nameMap, tempCount)))
      return failure();

    // Signal host that compute is done (required by SDK memcpy infrastructure).
    //
    // EXCEPTION: if the function body contains an async builtin call that
    // activates a completion task (e.g. async fmovs from a stream put/get),
    // the activation task itself is responsible for `unblock_cmd_stream`
    // once the fabric transfer has finished. Emitting `unblock_cmd_stream`
    // at the end of the function body too would let the host's memcpy_d2h
    // proceed BEFORE the fabric data has arrived, returning stale (zero)
    // bytes and causing a "received length 0 bytes" error.
    bool hasAsyncActivation = false;
    funcOp.walk([&](cslns::BuiltinCallOp bc) {
      if (bc->hasAttr("async") && bc->hasAttr("activate"))
        hasAsyncActivation = true;
    });
    if (!hasAsyncActivation)
      os << "  sys_mod.unblock_cmd_stream();\n";
    os << "}\n\n";
  }

  // 3.5 Emit csl.task ops. Two trigger forms:
  //   - "local_task_id" + id : emit a `<sym>_id: local_task_id` const, the
  //     task body, then a comptime block binding the task to the id.
  //   - "color"             : emit just the task body + a comptime block
  //     binding the task to the named color.
  for (Operation &op : prog.getBody().front()) {
    auto taskOp = dyn_cast<cslns::TaskOp>(&op);
    if (!taskOp) continue;

    StringRef triggerKind = taskOp.getTriggerKind();
    StringRef sym = taskOp.getSymName();

    if (triggerKind == "local_task_id") {
      auto idAttr = taskOp.getIdAttr();
      if (!idAttr) {
        taskOp.emitOpError(
            "CSLEmit: csl.task with trigger_kind \"local_task_id\" "
            "requires an `id` attribute");
        return failure();
      }
      os << "const " << sym << "_id: local_task_id = @get_local_task_id("
         << idAttr.getInt() << ");\n";
    } else if (triggerKind != "color") {
      taskOp.emitOpError("CSLEmit: csl.task has unknown trigger_kind '")
          << triggerKind << "'";
      return failure();
    }

    os << "task " << sym << "() void {\n";
    llvm::DenseMap<Value, std::string> nameMap;
    for (auto &kv : outerMap)
      nameMap[kv.first] = kv.second;
    unsigned tempCount = 0;
    if (failed(emitFuncBody(taskOp.getBody(), os, /*indentLevel=*/1,
                            outerMap, nameMap, tempCount)))
      return failure();
    os << "}\n";

    if (triggerKind == "local_task_id") {
      os << "comptime { @bind_local_task(" << sym << ", " << sym
         << "_id); }\n\n";
    } else {
      auto colorAttr = taskOp.getColorAttr();
      if (!colorAttr) {
        taskOp.emitOpError(
            "CSLEmit: csl.task with trigger_kind \"color\" "
            "requires a `color` symbol attribute");
        return failure();
      }
      os << "comptime { @bind_local_task(" << sym << ", "
         << colorAttr.getValue() << "); }\n\n";
    }
  }

  // 4. Emit comptime block for csl.export ops (direction != "internal")
  bool hasExports = false;
  for (Operation &op : prog.getBody().front()) {
    if (auto expOp = dyn_cast<cslns::ExportOp>(&op)) {
      auto dir = expOp.getDirection();
      auto kind = expOp.getKind();
      bool isFuncExport = kind.has_value() && *kind == "func";
      if (!isFuncExport && dir.has_value() && *dir == "internal")
        continue;
      if (!hasExports) {
        os << "comptime {\n";
        hasExports = true;
      }
      StringRef sym = expOp.getSym();
      if (isFuncExport) {
        os << "  @export_symbol(" << sym << ");\n";
      } else {
        StringRef alias = expOp.getAlias().value_or(sym);
        os << "  @export_symbol(" << sym << "_ptr, \"" << alias << "\");\n";
      }
    }
  }
  if (hasExports)
    os << "}\n";

  return success();
}

} // namespace

// Wafer-scoped entry point used by CSLEmitAll.cpp.
LogicalResult runProgramEmitter(xilinx::csl::WaferOp wafer,
                                llvm::raw_ostream &os) {
  ProgramEmitter emitter(os);
  return emitter.emit(wafer);
}

// Program-scoped entry point used by CSLEmitAll.cpp for multi-program wafers.
LogicalResult runProgramEmitter(xilinx::csl::ProgramOp prog,
                                llvm::raw_ostream &os) {
  ProgramEmitter emitter(os);
  return emitter.emitProgram(prog);
}

// Module-scoped entry point for backward compatibility (--emit-csl-program).
LogicalResult runProgramEmitter(ModuleOp module, llvm::raw_ostream &os) {
  namespace cslns = xilinx::csl;
  // Collect all wafers so we can emit a note if there are multiple.
  llvm::SmallVector<cslns::WaferOp, 4> wafers;
  module.walk([&](cslns::WaferOp w) { wafers.push_back(w); });
  if (wafers.empty()) {
    os << "// No csl.wafer found in module.\n";
    return success();
  }
  if (wafers.size() > 1)
    os << "// note: " << wafers.size()
       << " wafers in module; emitting " << wafers[0].getSymName() << "\n";
  return runProgramEmitter(wafers[0], os);
}

void registerCSLProgramTranslation() {
  static TranslateFromMLIRRegistration reg(
      "emit-csl-program",
      "Emit CSL v2 PE program source (program.csl) from csl.program",
      [](ModuleOp module, llvm::raw_ostream &os) -> LogicalResult {
        return runProgramEmitter(module, os);
      },
      [](DialectRegistry &registry) {
        registry.insert<xilinx::csl::CSLDialect,
                        xilinx::csl_layout::CSLLayoutDialect,
                        xilinx::csl_host::CSLHostDialect,
                        mlir::arith::ArithDialect,
                        mlir::func::FuncDialect,
                        mlir::memref::MemRefDialect,
                        mlir::scf::SCFDialect>();
      });
}

} // namespace csl
} // namespace xilinx
