//===- CSLProgramEmitter.cpp - Emit PE program.csl -------------*- C++ -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// Registers --emit-csl-program. Walks csl.wafer > csl.program and emits the
// PE-level CSL source text.
//
//===----------------------------------------------------------------------===//

#include "CSLEmitCommon.h"

#include "air/Dialect/CSL/CSLDialect.h"
#include "air/Dialect/CSL/CSLHostOps.h"
#include "air/Dialect/CSL/CSLLayoutOps.h"
#include "air/Dialect/CSL/CSLOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/raw_ostream.h"

#include <string>

using namespace mlir;
using xilinx::csl::detail::cslTypeName;
using xilinx::csl::detail::emitFuncBody;

namespace xilinx {
namespace csl {

namespace {

class ProgramEmitter {
public:
  explicit ProgramEmitter(llvm::raw_ostream &os) : os(os) {}
  LogicalResult emit(ModuleOp module);

private:
  llvm::raw_ostream &os;
};

LogicalResult ProgramEmitter::emit(ModuleOp module) {
  namespace cslns = xilinx::csl;

  // Find csl.wafer
  cslns::WaferOp wafer;
  module.walk([&](cslns::WaferOp w) { wafer = w; });
  if (!wafer) {
    os << "// No csl.wafer found in module.\n";
    return success();
  }

  // Find the first csl.program
  cslns::ProgramOp prog;
  wafer.walk([&](cslns::ProgramOp p) {
    if (!prog) prog = p;
  });
  if (!prog) {
    os << "// No csl.program found in csl.wafer.\n";
    return success();
  }

  os << "// Generated by air-translate --emit-csl-program\n\n";

  // Emit memcpy module preamble (required for SDK host communication).
  os << "param memcpy_params: comptime_struct;\n";
  os << "const sys_mod = @import_module(\"<memcpy/memcpy>\", memcpy_params);\n\n";

  // 1. Emit param declarations from block args with !csl.comptime<T> type.
  Region &progBody = prog.getBody();
  if (!progBody.empty()) {
    Block &entryBlock = progBody.front();
    for (BlockArgument arg : entryBlock.getArguments()) {
      Type t = arg.getType();
      if (auto comptime = mlir::dyn_cast<cslns::ComptimeType>(t)) {
        std::string argName = "arg" + std::to_string(arg.getArgNumber());
        os << "param " << argName << ": " << cslTypeName(comptime.getInnerType())
           << ";\n";
      }
    }
    os << "\n";
  }

  // Build outer map: csl.var SSA results → sym_name
  llvm::DenseMap<Value, std::string> outerMap;

  // 2. Emit var declarations
  bool hasVars = false;
  for (Operation &op : prog.getBody().front()) {
    if (auto varOp = dyn_cast<cslns::VarOp>(&op)) {
      auto memTy = dyn_cast<MemRefType>(varOp.getResult().getType());
      if (!memTy || memTy.getRank() != 1) {
        varOp.emitOpError("CSLEmit: csl.var must have 1-D memref type");
        return failure();
      }
      std::string eltName = cslTypeName(memTy.getElementType());
      int64_t dim = memTy.getDimSize(0);
      os << "var " << varOp.getSymName() << ": [" << dim << "]" << eltName
         << ";\n";
      outerMap[varOp.getResult()] = varOp.getSymName().str();
      hasVars = true;
    }
  }
  if (hasVars)
    os << "\n";

  // Emit pointer variables for exported buffers (SDK memcpy requirement).
  // Direction determines mutability: "in" → var (host writes), "out" → const (host reads).
  bool hasPointers = false;
  for (Operation &op : prog.getBody().front()) {
    if (auto expOp = dyn_cast<cslns::ExportOp>(&op)) {
      auto kind = expOp.getKind();
      if (kind.has_value() && *kind == "func")
        continue; // function exports don't need pointers

      auto dir = expOp.getDirection();
      if (dir.has_value() && *dir == "internal")
        continue;

      StringRef sym = expOp.getSym();

      // Find the var op to get element type
      std::string eltName = "f32"; // default
      for (Operation &varOp : prog.getBody().front()) {
        if (auto v = dyn_cast<cslns::VarOp>(&varOp)) {
          if (v.getSymName() == sym) {
            if (auto memTy = dyn_cast<MemRefType>(v.getResult().getType()))
              eltName = cslTypeName(memTy.getElementType());
            break;
          }
        }
      }

      bool isOutput = dir.has_value() && *dir == "out";
      os << (isOutput ? "const " : "var ") << sym << "_ptr: [*]" << eltName
         << " = &" << sym << ";\n";
      hasPointers = true;
    }
  }
  if (hasPointers)
    os << "\n";

  // 3. Emit function definitions
  for (Operation &op : prog.getBody().front()) {
    auto funcOp = dyn_cast<cslns::FuncOp>(&op);
    if (!funcOp) continue;

    os << "fn " << funcOp.getSymName() << "() void {\n";

    llvm::DenseMap<Value, std::string> nameMap;
    for (auto &kv : outerMap)
      nameMap[kv.first] = kv.second;

    unsigned tempCount = 0;
    if (failed(emitFuncBody(funcOp.getBody(), os, /*indentLevel=*/1,
                            outerMap, nameMap, tempCount)))
      return failure();

    // Signal host that compute is done (required by SDK memcpy infrastructure).
    os << "  sys_mod.unblock_cmd_stream();\n";
    os << "}\n\n";
  }

  // 4. Emit comptime block for csl.export ops (direction != "internal")
  bool hasExports = false;
  for (Operation &op : prog.getBody().front()) {
    if (auto expOp = dyn_cast<cslns::ExportOp>(&op)) {
      auto dir = expOp.getDirection();
      auto kind = expOp.getKind();
      bool isFuncExport = kind.has_value() && *kind == "func";
      if (!isFuncExport && dir.has_value() && *dir == "internal")
        continue;
      if (!hasExports) {
        os << "comptime {\n";
        hasExports = true;
      }
      StringRef sym = expOp.getSym();
      if (isFuncExport) {
        os << "  @export_symbol(" << sym << ");\n";
      } else {
        StringRef alias = expOp.getAlias().value_or(sym);
        os << "  @export_symbol(" << sym << "_ptr, \"" << alias << "\");\n";
      }
    }
  }
  if (hasExports)
    os << "}\n";

  return success();
}

} // namespace

// Free-function entry point used by CSLEmitAll.cpp.
LogicalResult runProgramEmitter(ModuleOp module, llvm::raw_ostream &os) {
  ProgramEmitter emitter(os);
  return emitter.emit(module);
}

void registerCSLProgramTranslation() {
  static TranslateFromMLIRRegistration reg(
      "emit-csl-program",
      "Emit CSL v2 PE program source (program.csl) from csl.program",
      [](ModuleOp module, llvm::raw_ostream &os) -> LogicalResult {
        return runProgramEmitter(module, os);
      },
      [](DialectRegistry &registry) {
        registry.insert<xilinx::csl::CSLDialect,
                        xilinx::csl_layout::CSLLayoutDialect,
                        xilinx::csl_host::CSLHostDialect,
                        mlir::arith::ArithDialect,
                        mlir::func::FuncDialect,
                        mlir::memref::MemRefDialect,
                        mlir::scf::SCFDialect>();
      });
}

} // namespace csl
} // namespace xilinx
