#!/usr/bin/env cs_python
# Auto-generated by air-translate --emit-csl

import argparse
import numpy as np
from cerebras.geometry.geometry import IntVector, IntRectangle
from cerebras.sdk.runtime.sdkruntimepybind import (
    SdkLayout, SdkTarget, SdkRuntime, SimfabConfig, get_platform,
)

parser = argparse.ArgumentParser()
parser.add_argument('--cmaddr', help='IP:port for CS system')
parser.add_argument('--arch', choices=['wse2', 'wse3'], default='wse3',
    help='Target WSE architecture (default: wse3)')
args = parser.parse_args()

###########
### Parameters
###########
batch_size = 4
batch_size = 4
batch_size = 4
batch_size = 4
batch_width = 4
batch_height = 8
batch_size = 8

###########
### Layout
###########
config = SimfabConfig(dump_core=True)
target = SdkTarget.WSE3 if (args.arch == 'wse3') else SdkTarget.WSE2
platform = get_platform(args.cmaddr, config, target)
layout = SdkLayout(platform)

x_in = Color('x_in')
b_in = Color('b_in')
y_out = Color('y_out')
x_host = Color('x_host')


x_demux_adaptor = layout.create_code_region('./demux_adaptor.csl', 'x_demux_adaptor', 1, 1)
x_demux_adaptor.set_param_all('batch_size', 4)
x_demux_adaptor.set_param_all(x_host)
x_demux_adaptor.set_param_all(x_in)



x_demux_adaptor.place(0, 0)
x_demux = layout.create_code_region('./demux.csl', 'x_demux', 4, 1)
rp_0 = RoutingPosition().set_input([Route.NORTH]).set_output([Route.RAMP, Route.SOUTH])
rp_1 = RoutingPosition().set_input([Route.NORTH]).set_output([Route.RAMP])
er_2 = get_edge_routing(Edge.RIGHT, [rp_1])
x_demux.set_param_all('batch_size', 4)
x_demux.set_param_all(x_in)
x_demux.paint_all(x_in, [rp_0], [er_2])
x_demux.place(0, 1)
b_demux_adaptor = layout.create_code_region('./demux_adaptor.csl', 'b_demux_adaptor', 1, 1)
b_demux_adaptor.set_param_all('batch_size', 4)
b_demux_adaptor.set_param_all(b_in)
b_demux_adaptor.place(4, 2)
b_demux = layout.create_code_region('./demux.csl', 'b_demux', 1, 4)
rp_3 = RoutingPosition().set_input([Route.WEST]).set_output([Route.RAMP, Route.EAST])
b_demux.set_param_all('batch_size', 4)
b_demux.set_param_all(b_in)
b_demux.paint_all(b_in, [rp_3])
b_demux.place(0, 2)
gemv = layout.create_code_region('./gemv.csl', 'gemv', 4, 4)
rp_4 = RoutingPosition().set_input([Route.NORTH]).set_output([Route.RAMP])
rp_5 = RoutingPosition().set_input([Route.NORTH]).set_output([Route.RAMP])
er_6 = get_edge_routing(Edge.BOTTOM, [rp_5])
rp_7 = RoutingPosition().set_output([Route.WEST])
gemv.set_param_all('batch_width', 4)
gemv.set_param_all('batch_height', 8)
gemv.set_param_all(x_in)
gemv.set_param_all(y_out)
gemv.paint_all(x_in, [rp_4], [er_6])
gemv.paint_range(IntRectangle(IntVector(0, 0), IntVector(1, 4)), y_out, [rp_7])
gemv.set_param_range(IntRectangle(IntVector(0, 0), IntVector(4, 4)), x_in)
gemv.set_param_range(IntRectangle(IntVector(1, 0), IntVector(2, 4)), 'b_in', y_out)
gemv.place(0, 2)
y_mux = layout.create_code_region('./mux.csl', 'y_mux', 1, 4)
rp_8 = RoutingPosition().set_input([Route.EAST]).set_output([Route.RAMP])
y_mux.set_param_all('batch_size', 8)
y_mux.set_param_all(y_out)
y_mux.paint_all(y_out, [rp_8])
y_mux.place(5, 2)
rp_9 = RoutingPosition().set_input([Route.RAMP])
port10 = x_demux_adaptor.create_input_port(x_host, Edge.LEFT, [rp_9], 16)
rp_11 = RoutingPosition().set_output([Route.RAMP])
port12 = y_mux.create_output_port(y_out, Edge.RIGHT, [rp_11], 32)
layout.connect(port10, port12)
in_stream13 = layout.create_input_stream(port10)

compile_artifacts = layout.compile(out_prefix='out')

############
### Runtime
############
runtime = SdkRuntime(compile_artifacts, platform, memcpy_required=False)
runtime.load()
runtime.run()
# runtime.send(in_stream13, data, nonblock=True)   # TODO: fill in data
runtime.stop()

#################
### Verification
#################
result_result = runtime.read_symbol(0, 0, 'result', dtype='uint32')

print("SUCCESS!")
