// RUN: split-file %s %t
// RUN: air-translate --emit-csl-layout %t/vecadd.mlir | FileCheck %s --check-prefix=CHECK-VECADD
// RUN: air-translate --emit-csl-layout %t/gemv.mlir   | FileCheck %s --check-prefix=CHECK-GEMV
//
// Verifies --emit-csl-layout output for a 1x1 vecadd program and a
// parameterized gemv program.
//
// vecadd: checks create_code_region uses sym_name and place(0, 0) is emitted.
// gemv:   checks set_param_all is emitted for each comptime param.

// CHECK-VECADD: # Generated by air-translate --emit-csl-layout
// CHECK-VECADD: from cerebras.sdk.runtime.sdkruntimepybind import SdkLayout, SdkTarget
// CHECK-VECADD: def get_layout(target: SdkTarget) -> SdkLayout:
// CHECK-VECADD:     layout = SdkLayout(target)
// CHECK-VECADD:     region = layout.create_code_region("vecadd_pe.csl", "vecadd_pe", 1, 1)
// CHECK-VECADD:     region.place(0, 0)
// CHECK-VECADD:     return layout

// CHECK-GEMV: region = layout.create_code_region("gemv_pe.csl", "gemv_pe", 1, 1)
// CHECK-GEMV:     region.set_param_all("M", 4)
// CHECK-GEMV:     region.set_param_all("N", 6)
// CHECK-GEMV:     region.place(0, 0)

//--- vecadd.mlir
module {
  csl.wafer @vecadd {arch = "wse3"} {
    csl.program @vecadd_pe {
      %a = csl.var @a : memref<256xf32>
      %b = csl.var @b : memref<256xf32>
      %c = csl.var @c : memref<256xf32>
      csl.func @compute { csl.return }
      csl.export @a {alias = "a"}
      csl.export @b {alias = "b"}
      csl.export @c {alias = "c"}
      csl.export @compute {kind = "func"}
    }
    csl.layout {width = 1 : i64, height = 1 : i64} @main_layout {
      csl_layout.place @vecadd_pe at (0, 0)
      csl_layout.export "a" from @vecadd_pe::@a
      csl_layout.export "b" from @vecadd_pe::@b
      csl_layout.export "c" from @vecadd_pe::@c
      csl_layout.export "compute" from @vecadd_pe::@compute {kind = "func"}
    }
    csl.host @main(%a_in: memref<256xf32>, %b_in: memref<256xf32>,
                   %c_out: memref<256xf32>) {layout = @main_layout} {
    }
  }
}

//--- gemv.mlir
module {
  csl.wafer @gemv {arch = "wse3"} {
    csl.program @gemv_pe(%M: !csl.comptime<i16>, %N: !csl.comptime<i16>) {
    }
    csl.layout {width = 4 : i64, height = 1 : i64} @gemv_layout {
      csl_layout.place @gemv_pe at (0, 0) {M = 4 : i16, N = 6 : i16}
    }
    csl.host @main() {layout = @gemv_layout} {
    }
  }
}
