// RUN: air-opt -csl-infer-exports %s | air-translate --emit-csl-host | FileCheck %s
//
// Verifies --emit-csl-host output for a 1x1 vecadd program.
// Checks: import lines, def main signature, memcpy calls, launch call.

// CHECK: # Generated by air-translate --emit-csl-host
// CHECK: from csl_layout import get_layout
// CHECK: from cerebras.sdk.client import SdkRuntime
// CHECK: import numpy as np
// CHECK: def main(target, arg0, arg1, arg2):
// CHECK:     artifacts = get_layout(target).compile("out/")
// CHECK:     N = 256
// CHECK:     with SdkRuntime(artifacts) as runner:
// CHECK:         runner.memcpy_h2d(runner.get_id("a"), arg0, 0, 0, 1, 1, N)
// CHECK:         runner.memcpy_h2d(runner.get_id("b"), arg1, 0, 0, 1, 1, N)
// CHECK:         runner.launch("compute", nonblock=False)
// CHECK:         runner.memcpy_d2h(arg2, runner.get_id("c"), 0, 0, 1, 1, N)

module {
  csl.wafer @vecadd {arch = "wse3"} {
    csl.program @vecadd_pe {
      %a = csl.var @a : memref<256xf32>
      %b = csl.var @b : memref<256xf32>
      %c = csl.var @c : memref<256xf32>
      csl.func @compute { csl.return }
      csl.export @a {alias = "a"}
      csl.export @b {alias = "b"}
      csl.export @c {alias = "c"}
      csl.export @compute {kind = "func"}
    }
    csl.layout {width = 1 : i64, height = 1 : i64} @main_layout {
      csl_layout.place @vecadd_pe at (0, 0)
      csl_layout.export "a" from @vecadd_pe::@a
      csl_layout.export "b" from @vecadd_pe::@b
      csl_layout.export "c" from @vecadd_pe::@c
      csl_layout.export "compute" from @vecadd_pe::@compute {kind = "func"}
    }
    csl.host @main(%a_in: memref<256xf32>, %b_in: memref<256xf32>,
                   %c_out: memref<256xf32>) {layout = @main_layout} {
      csl_host.memcpy_h2d %a_in to @main_layout::@a
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
      csl_host.memcpy_h2d %b_in to @main_layout::@b
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
      csl_host.launch @main_layout::@compute
      csl_host.memcpy_d2h @main_layout::@c to %c_out
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
    }
  }
}
