#!/usr/bin/env cs_python
# Generated by air-translate --emit-csl-host
#
# Run against a pre-compiled artifact directory produced by
#   cslc layout.csl --arch=wseN ... -o <dir> --memcpy --channels 1
# The companion commands_wse{2,3}.sh scripts do both steps.

import argparse
import sys
import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import (
    SdkRuntime,
    MemcpyOrder,
    MemcpyDataType,
)

parser = argparse.ArgumentParser()
parser.add_argument('--name', default='compiled',
                    help='compiled artifact directory (default: compiled)')
parser.add_argument('--cmaddr', default=None,
                    help='IP:port for CS system (default: simulator)')
args = parser.parse_args()

N = 64

# Host buffers.
arg0 = np.arange(N, dtype=np.float32)
arg1 = np.arange(N, dtype=np.float32) * 2.0
arg2 = np.zeros(N, dtype=np.float32)
arg3 = np.zeros(N, dtype=np.float32)

# Create runtime and load compiled artifacts.
runner = SdkRuntime(args.name, cmaddr=args.cmaddr, simfab_numthreads=32)
runner.load()
runner.run()

# Host-to-device copies (inputs).
runner.memcpy_h2d(runner.get_id("a"), arg0, 0, 0, 1, 1, 64,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)
runner.memcpy_h2d(runner.get_id("b"), arg1, 0, 0, 1, 1, 64,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)

# Launch compute kernel.
runner.launch("compute", nonblock=False)

# Device-to-host copies (outputs).
runner.memcpy_d2h(arg2, runner.get_id("c"), 0, 0, 1, 1, 64,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)
runner.memcpy_d2h(arg3, runner.get_id("d"), 0, 0, 1, 1, 64,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)

runner.stop()

# Reference computation (numpy, interpreted from csl.func @compute body).
_a_ref = arg0[:64].astype(np.float32).copy()
_b_ref = arg1[:64].astype(np.float32).copy()
_c_ref = np.zeros(64, dtype=np.float32)
_d_ref = np.zeros(64, dtype=np.float32)
for i3 in range(0, 64, 1):
    t4 = _a_ref[i3]
    t5 = _b_ref[i3]
    t6 = t4 + t5
    t7 = t4 * t5
    _c_ref[i3] = t6
    _d_ref[i3] = t7

# Verification: compare each D2H output against its reference.
_mismatch = False
_expected_arg2 = np.zeros_like(arg2)
_expected_arg2[:64] = _c_ref
if not np.allclose(arg2, _expected_arg2, atol=1e-5, rtol=1e-5):
    print("MISMATCH in arg2 (var @c):", file=sys.stderr)
    print(f"  expected[:8] = {_expected_arg2[:min(8, len(_expected_arg2))]}", file=sys.stderr)
    print(f"  got[:8]      = {arg2[:min(8, len(arg2))]}", file=sys.stderr)
    _mismatch = True
else:
    print(f"  arg2[:8] = {arg2[:min(8, len(arg2))]} (matches reference)")
_expected_arg3 = np.zeros_like(arg3)
_expected_arg3[:64] = _d_ref
if not np.allclose(arg3, _expected_arg3, atol=1e-5, rtol=1e-5):
    print("MISMATCH in arg3 (var @d):", file=sys.stderr)
    print(f"  expected[:8] = {_expected_arg3[:min(8, len(_expected_arg3))]}", file=sys.stderr)
    print(f"  got[:8]      = {arg3[:min(8, len(arg3))]}", file=sys.stderr)
    _mismatch = True
else:
    print(f"  arg3[:8] = {arg3[:min(8, len(arg3))]} (matches reference)")
if _mismatch:
    sys.exit(1)
print("SUCCESS!")
