// RUN: air-opt -csl-infer-exports %s | air-translate --emit-csl-program | FileCheck %s
//
// Verifies --emit-csl-program output for a 1x1 vecadd program.
// Key check: @compute with kind="func" MUST appear in comptime block
// even though -csl-infer-exports sets direction="internal" on it.
// Negative check: a plain internal export (no kind) must NOT be emitted.

// CHECK: // Generated by air-translate --emit-csl-program
// CHECK: param memcpy_params: comptime_struct;
// CHECK: const sys_mod = @import_module("<memcpy/memcpy>", memcpy_params);
// CHECK: var a: [256]f32;
// CHECK: var b: [256]f32;
// CHECK: var c: [256]f32;
// CHECK: var a_ptr: [*]f32 = &a;
// CHECK: var b_ptr: [*]f32 = &b;
// CHECK: const c_ptr: [*]f32 = &c;
// CHECK-NOT: a_internal_ptr
// CHECK: fn compute() void {
// CHECK:   var i0: u16 = 0;
// CHECK:   while (i0 < 256) : (i0 += 1) {
// CHECK:     var t1 = a[i0];
// CHECK:     var t2 = b[i0];
// CHECK:     var t3: f32 = t1 + t2;
// CHECK:     c[i0] = t3;
// CHECK:   }
// CHECK:   sys_mod.unblock_cmd_stream();
// CHECK: }
// CHECK: comptime {
// CHECK-NOT: @export_symbol(a_internal
// CHECK:   @export_symbol(a_ptr, "a");
// CHECK:   @export_symbol(b_ptr, "b");
// CHECK:   @export_symbol(c_ptr, "c");
// CHECK:   @export_symbol(compute);
// CHECK: }

module {
  csl.wafer @vecadd {arch = "wse3"} {
    csl.program @vecadd_pe {
      %a = csl.var @a : memref<256xf32>
      %b = csl.var @b : memref<256xf32>
      %c = csl.var @c : memref<256xf32>
      csl.func @compute {
        %lo = arith.constant 0 : index
        %hi = arith.constant 256 : index
        %step = arith.constant 1 : index
        scf.for %i = %lo to %hi step %step {
          %va = memref.load %a[%i] : memref<256xf32>
          %vb = memref.load %b[%i] : memref<256xf32>
          %vc = arith.addf %va, %vb : f32
          memref.store %vc, %c[%i] : memref<256xf32>
        }
        csl.return
      }
      %a_internal = csl.var @a_internal : memref<1xf32>
      csl.export @a {alias = "a"}
      csl.export @b {alias = "b"}
      csl.export @c {alias = "c"}
      csl.export @compute {kind = "func"}
      csl.export @a_internal {direction = "internal"}
    }
    csl.layout {width = 1 : i64, height = 1 : i64} @main_layout {
      csl_layout.place @vecadd_pe at (0, 0)
      csl_layout.export "a" from @vecadd_pe::@a
      csl_layout.export "b" from @vecadd_pe::@b
      csl_layout.export "c" from @vecadd_pe::@c
      csl_layout.export "compute" from @vecadd_pe::@compute {kind = "func"}
    }
    csl.host @main(%a_in: memref<256xf32>, %b_in: memref<256xf32>,
                   %c_out: memref<256xf32>) {layout = @main_layout} {
      csl_host.memcpy_h2d %a_in to @main_layout::@a
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
      csl_host.memcpy_h2d %b_in to @main_layout::@b
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
      csl_host.launch @main_layout::@compute
      csl_host.memcpy_d2h @main_layout::@c to %c_out
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
    }
  }
}
