// RUN: air-opt -csl-infer-exports %s | air-translate --emit-csl-host | FileCheck %s
//
// Verifies --emit-csl-host output for a 1x1 vecadd program.
// The emitter produces a complete runnable cs_python script that targets
// the precompiled-artifact flow:
//   runner = SdkRuntime(args.name, cmaddr=args.cmaddr)
// ...then runs h2d -> launch -> d2h -> stop -> prints SUCCESS!.

// CHECK: #!/usr/bin/env cs_python
// CHECK: # Generated by air-translate --emit-csl-host
// CHECK: import argparse
// CHECK: import numpy as np
// CHECK: from cerebras.sdk.runtime.sdkruntimepybind import (
// CHECK:     SdkRuntime,
// CHECK:     MemcpyOrder,
// CHECK:     MemcpyDataType,
// CHECK: )
// CHECK: parser = argparse.ArgumentParser()
// CHECK: parser.add_argument('--name'
// CHECK: parser.add_argument('--cmaddr'
// CHECK: N = 256
// CHECK: arg0 = np.arange(N, dtype=np.float32)
// CHECK: arg1 = np.arange(N, dtype=np.float32) * 2.0
// CHECK: arg2 = np.zeros(N, dtype=np.float32)
// CHECK: runner = SdkRuntime(args.name, cmaddr=args.cmaddr)
// CHECK: runner.load()
// CHECK: runner.run()
// CHECK: runner.memcpy_h2d(runner.get_id("a"), arg0, 0, 0, 1, 1, 256,
// CHECK:                   data_type=MemcpyDataType.MEMCPY_32BIT,
// CHECK: runner.memcpy_h2d(runner.get_id("b"), arg1, 0, 0, 1, 1, 256,
// CHECK: runner.launch("compute", nonblock=False)
// CHECK: runner.memcpy_d2h(arg2, runner.get_id("c"), 0, 0, 1, 1, 256,
// CHECK: runner.stop()
// CHECK: print("SUCCESS!")

module {
  csl.wafer @vecadd {arch = "wse3"} {
    csl.program @vecadd_pe {
      %a = csl.var @a : memref<256xf32>
      %b = csl.var @b : memref<256xf32>
      %c = csl.var @c : memref<256xf32>
      csl.func @compute { csl.return }
      csl.export @a {alias = "a"}
      csl.export @b {alias = "b"}
      csl.export @c {alias = "c"}
      csl.export @compute {kind = "func"}
    }
    csl.layout {width = 1 : i64, height = 1 : i64} @main_layout {
      csl_layout.place @vecadd_pe at (0, 0)
      csl_layout.export "a" from @vecadd_pe::@a
      csl_layout.export "b" from @vecadd_pe::@b
      csl_layout.export "c" from @vecadd_pe::@c
      csl_layout.export "compute" from @vecadd_pe::@compute {kind = "func"}
    }
    csl.host @main(%a_in: memref<256xf32>, %b_in: memref<256xf32>,
                   %c_out: memref<256xf32>) {layout = @main_layout} {
      csl_host.memcpy_h2d %a_in to @main_layout::@a
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
      csl_host.memcpy_h2d %b_in to @main_layout::@b
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
      csl_host.launch @main_layout::@compute
      csl_host.memcpy_d2h @main_layout::@c to %c_out
          {px = 0 : i64, py = 0 : i64, width = 1 : i64, height = 1 : i64}
          : memref<256xf32>
    }
  }
}
