#!/usr/bin/env cs_python
# Generated by air-translate --emit-csl-host
#
# Run against a pre-compiled artifact directory produced by
#   cslc layout.csl --arch=wseN ... -o <dir> --memcpy --channels 1
# The companion commands_wse{2,3}.sh scripts do both steps.

import argparse
import sys
import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import (
    SdkRuntime,
    MemcpyOrder,
    MemcpyDataType,
)

parser = argparse.ArgumentParser()
parser.add_argument('--name', default='compiled',
                    help='compiled artifact directory (default: compiled)')
parser.add_argument('--cmaddr', default=None,
                    help='IP:port for CS system (default: simulator)')
args = parser.parse_args()

N = 32

# Host buffers.
arg0 = np.zeros(N, dtype=np.float32)

# Create runtime and load compiled artifacts.
runner = SdkRuntime(args.name, cmaddr=args.cmaddr, simfab_numthreads=32)
runner.load()
runner.run()

# Host-to-device copies (inputs).

# Launch compute kernel.
runner.launch("compute", nonblock=False)

# Device-to-host copies (outputs).
runner.memcpy_d2h(arg0, runner.get_id("y"), 0, 0, 1, 1, 32,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)

runner.stop()

# Reference computation (numpy, interpreted from csl.func @compute body).
_y_ref = np.zeros(32, dtype=np.float32)

# Verification: compare each D2H output against its reference.
_mismatch = False
_expected_arg0 = np.zeros_like(arg0)
_expected_arg0[:32] = _y_ref
if not np.allclose(arg0, _expected_arg0, atol=1e-5, rtol=1e-5):
    print("MISMATCH in arg0 (var @y):", file=sys.stderr)
    print(f"  expected[:8] = {_expected_arg0[:min(8, len(_expected_arg0))]}", file=sys.stderr)
    print(f"  got[:8]      = {arg0[:min(8, len(arg0))]}", file=sys.stderr)
    _mismatch = True
else:
    print(f"  arg0[:8] = {arg0[:min(8, len(arg0))]} (matches reference)")
if _mismatch:
    sys.exit(1)
print("SUCCESS!")
