//===- CSLRuntimeToPy.cpp - Emit Python from csl_rt dialect -----*- C++ -*-===//
//
// Part of the air-to-csl project.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//
//
// Translation backend: csl_rt dialect → Python (single run.py file).
// Also extracts PE programs from csl.kernel ops.
//
// Pipeline:
//   csl.kernel (PE-level) + csl_rt ops (SDK-level)
//   → pe_program.csl (extracted from csl.kernel)
//   → run.py (complete script with inline build_layout function)
//
//===----------------------------------------------------------------------===//

#include "air/Dialect/CSL/CSLDialect.h"
#include "air/Dialect/CSL/CSLOps.h"
#include "air/Dialect/CSLRuntime/CSLRuntimeDialect.h"
#include "air/Dialect/CSLRuntime/CSLRuntimeOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Operation.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/CommandLine.h"
#include <map>
#include <set>
#include <string>
#include <vector>

using namespace mlir;
using namespace xilinx::csl_rt;

static llvm::cl::opt<std::string> cslOutputDir(
    "csl-output-dir",
    llvm::cl::desc("Output directory for layout.csl and pe_program.csl "
                   "(used with --emit-csl-rt)"),
    llvm::cl::init("."));

namespace {

//===----------------------------------------------------------------------===//
// LayoutEmitter
//
// Walks csl.spatial_placement + csl.code_region + csl.place + host-level
// csl.export_name ops and writes layout.csl to the output directory.
//===----------------------------------------------------------------------===//

class LayoutEmitter {
public:
  explicit LayoutEmitter(StringRef outDir) : outDir(outDir.str()) {}

  LogicalResult emit(ModuleOp module);

private:
  std::string outDir;

  static StringRef cslPtrType(Type elt) {
    if (elt.isF32()) return "[*]f32";
    if (elt.isF16()) return "[*]f16";
    if (elt.isInteger(32)) return "[*]i32";
    if (elt.isInteger(16)) return "[*]i16";
    return "[*]f32";
  }
};

LogicalResult LayoutEmitter::emit(ModuleOp module) {
  namespace cslns = xilinx::csl;

  // 1. Find the single csl.spatial_placement op.
  cslns::SpatialPlacementOp sp;
  module.walk([&](cslns::SpatialPlacementOp op) { sp = op; });
  if (!sp)
    return success(); // no-op: no spatial_placement means no layout to emit

  // 2. Find csl.code_region and csl.place inside the spatial_placement.
  cslns::CodeRegionOp region;
  cslns::PlaceOp place;
  sp.walk([&](Operation *op) {
    if (auto r = dyn_cast<cslns::CodeRegionOp>(op)) region = r;
    else if (auto p = dyn_cast<cslns::PlaceOp>(op)) place = p;
  });
  if (!region || !place) {
    sp.emitError("LayoutEmitter: expected exactly one code_region and one place");
    return failure();
  }

  // 3. Resolve kernel source_file from the defining csl.kernel op.
  //    place.getKernel() is the SSA value; its defining op is csl.kernel.
  auto kernelVal = place.getKernel();
  auto kernelOp = dyn_cast_or_null<cslns::KernelOp>(kernelVal.getDefiningOp());
  if (!kernelOp) {
    place.emitError("LayoutEmitter: csl.place kernel operand not defined by csl.kernel");
    return failure();
  }
  StringRef sourceFile = kernelOp.getSourceFile().value_or("pe.csl");
  uint64_t W = region.getWidth();
  uint64_t H = region.getHeight();
  uint64_t px = place.getX();
  uint64_t py = place.getY();

  // 4. Collect host-level csl.export_name ops from the first func.func found.
  //    They live in the host func body, not inside spatial_placement.
  func::FuncOp hostFunc;
  module.walk([&](func::FuncOp f) {
    if (!hostFunc) hostFunc = f;
  });
  if (!hostFunc) {
    sp.emitError("LayoutEmitter: no host function found in module");
    return failure();
  }

  // 5. Ensure the output directory exists and open layout.csl.
  if (auto ec = llvm::sys::fs::create_directories(outDir)) {
    llvm::errs() << "LayoutEmitter: failed to create output dir '"
                 << outDir << "': " << ec.message() << "\n";
    return failure();
  }
  llvm::SmallString<256> path(outDir);
  llvm::sys::path::append(path, "layout.csl");
  std::error_code ec;
  llvm::raw_fd_ostream os(path, ec);
  if (ec) {
    llvm::errs() << "LayoutEmitter: cannot open '" << path
                 << "': " << ec.message() << "\n";
    return failure();
  }

  // 6. Emit layout.csl.
  os << "// Generated by air-translate --emit-csl-rt (LayoutEmitter).\n\n";
  os << "const memcpy = @import_module(\"<memcpy/get_params>\", .{ .width = "
     << W << ", .height = " << H << " });\n\n";
  os << "layout {\n";
  os << "  @set_rectangle(" << W << ", " << H << ");\n";
  os << "  @set_tile_code(" << px << ", " << py << ", \"" << sourceFile
     << "\", .{ .memcpy_params = memcpy.get_params(0) });\n\n";

  for (auto &childOp : hostFunc.getBody().getOps()) {
    if (auto en = dyn_cast<cslns::ExportNameOp>(&childOp)) {
      StringRef name = en.getSymName();
      Type t = en.getExportedType();
      auto dir = en.getDirection();
      if (auto memTy = dyn_cast<MemRefType>(t)) {
        StringRef ptr = cslPtrType(memTy.getElementType());
        bool writable = dir.has_value() && *dir == "in";
        os << "  @export_name(\"" << name << "\", " << ptr << ", "
           << (writable ? "true" : "false") << ");\n";
      } else if (isa<FunctionType>(t)) {
        os << "  @export_name(\"" << name << "\", fn()void);\n";
      }
    }
  }
  os << "}\n";
  return success();
}

//===----------------------------------------------------------------------===//
// KernelEmitter
//
// Walks csl.kernel ops and writes one .csl file per kernel (e.g. vecadd_pe.csl)
// matching the hand-written golden reference.
//===----------------------------------------------------------------------===//

class KernelEmitter {
public:
  KernelEmitter(StringRef outDir, ModuleOp module)
      : outDir(outDir.str()), module(module) {}

  LogicalResult emit();

private:
  std::string outDir;
  ModuleOp module;

  // Map of host-level export name -> direction ("in"/"out"/function)
  // Built once from the host func's csl.export_name ops.
  std::map<std::string, std::string> hostExportDir; // name -> "in"/"out"/""(func)

  // Helpers
  static StringRef cslEltType(Type elt, Operation *op, bool &ok) {
    if (elt.isF32())   return "f32";
    if (elt.isF16())   return "f16";
    if (elt.isInteger(32)) return "i32";
    if (elt.isInteger(16)) return "i16";
    op->emitOpError("KernelEmitter: unsupported element type for CSL var");
    ok = false;
    return "f32";
  }

  /// Validate that every op in the kernel (recursively) is in the dispatch
  /// table. Returns failure() if anything is unknown.
  LogicalResult validateKernelOps(xilinx::csl::KernelOp kernelOp);

  /// Emit one kernel file. Returns failure() on error.
  LogicalResult emitKernel(xilinx::csl::KernelOp kernelOp,
                           llvm::raw_fd_ostream &os);

  /// Emit the body of a csl.func (the ops inside it), writing to os.
  LogicalResult emitFuncBody(xilinx::csl::FuncOp funcOp,
                             llvm::raw_fd_ostream &os,
                             llvm::DenseMap<mlir::Value, std::string> &nameMap,
                             unsigned &tempCount, unsigned indent);
};

// -------- helpers --------

static bool isKernelOpAllowed(Operation *op) {
  return isa<xilinx::csl::VarOp>(op) ||
         isa<xilinx::csl::FuncOp>(op) ||
         isa<xilinx::csl::ReturnOp>(op) ||
         isa<xilinx::csl::ExportSymbolOp>(op) ||
         isa<arith::ConstantOp>(op) ||
         isa<scf::ForOp>(op) ||
         isa<scf::YieldOp>(op) ||
         isa<memref::LoadOp>(op) ||
         isa<memref::StoreOp>(op) ||
         isa<arith::AddFOp>(op);
}

LogicalResult KernelEmitter::validateKernelOps(xilinx::csl::KernelOp kernelOp) {
  namespace cslns = xilinx::csl;
  LogicalResult result = success();

  // Walk all ops in the kernel body recursively.
  kernelOp.walk([&](Operation *op) {
    // Skip the kernel itself and csl.func containers (they are allowed wrappers)
    if (op == kernelOp.getOperation()) return WalkResult::advance();
    if (isa<cslns::KernelOp>(op))       return WalkResult::advance();
    if (isa<cslns::FuncOp>(op))         return WalkResult::advance();
    // For scf.for, validate preconditions
    if (auto forOp = dyn_cast<scf::ForOp>(op)) {
      auto loOp = forOp.getLowerBound().getDefiningOp<arith::ConstantIndexOp>();
      auto stepOp = forOp.getStep().getDefiningOp<arith::ConstantIndexOp>();
      auto hiOp = forOp.getUpperBound().getDefiningOp<arith::ConstantIndexOp>();
      if (!loOp || loOp.value() != 0 || !stepOp || stepOp.value() != 1 || !hiOp) {
        op->emitOpError("KernelEmitter: scf.for requires lo=0, step=1, constant hi");
        result = failure();
      }
      return WalkResult::advance();
    }
    if (!isKernelOpAllowed(op)) {
      op->emitOpError(
          llvm::Twine("KernelEmitter: unsupported MLIR op for CSL kernel emission: ") +
          op->getName().getStringRef());
      result = failure();
    }
    return WalkResult::advance();
  });

  return result;
}

LogicalResult KernelEmitter::emit() {
  namespace cslns = xilinx::csl;

  // Collect host-level csl.export_name ops from the first func.func.
  func::FuncOp hostFunc;
  module.walk([&](func::FuncOp f) {
    if (!hostFunc) hostFunc = f;
  });
  if (hostFunc) {
    for (auto &op : hostFunc.getBody().getOps()) {
      if (auto en = dyn_cast<cslns::ExportNameOp>(&op)) {
        std::string name = en.getSymName().str();
        auto dir = en.getDirection();
        if (dir.has_value())
          hostExportDir[name] = dir->str();
        else
          hostExportDir[name] = ""; // function export
      }
    }
  }

  // Ensure output directory exists.
  if (auto ec = llvm::sys::fs::create_directories(outDir)) {
    llvm::errs() << "KernelEmitter: failed to create output dir '"
                 << outDir << "': " << ec.message() << "\n";
    return failure();
  }

  // Find and emit each csl.kernel.
  LogicalResult result = success();
  module.walk([&](cslns::KernelOp kernelOp) {
    if (failed(result)) return;

    // Validate before opening any file.
    if (failed(validateKernelOps(kernelOp))) {
      result = failure();
      return;
    }

    StringRef sourceFile = kernelOp.getSourceFile().value_or("pe.csl");

    llvm::SmallString<256> path(outDir);
    llvm::sys::path::append(path, sourceFile);
    std::error_code ec;
    llvm::raw_fd_ostream os(path, ec);
    if (ec) {
      llvm::errs() << "KernelEmitter: cannot open '" << path
                   << "': " << ec.message() << "\n";
      result = failure();
      return;
    }

    if (failed(emitKernel(kernelOp, os)))
      result = failure();
  });

  return result;
}

// Write indentation
static void writeIndent(llvm::raw_fd_ostream &os, unsigned level) {
  for (unsigned i = 0; i < level; ++i)
    os << "  ";
}

LogicalResult KernelEmitter::emitFuncBody(xilinx::csl::FuncOp funcOp,
                                          llvm::raw_fd_ostream &os,
                                          llvm::DenseMap<mlir::Value, std::string> &nameMap,
                                          unsigned &tempCount, unsigned indent) {
  for (auto &op : funcOp.getBody().getOps()) {
    if (isa<xilinx::csl::ReturnOp>(op)) {
      // Nothing emitted for csl.return
      continue;
    }
    if (isa<scf::YieldOp>(op)) {
      // Nothing emitted for scf.yield
      continue;
    }
    if (auto constOp = dyn_cast<arith::ConstantOp>(op)) {
      // Map SSA value to literal string — inline at use site
      if (auto intAttr = dyn_cast<IntegerAttr>(constOp.getValue())) {
        nameMap[constOp.getResult()] = std::to_string(intAttr.getInt());
      }
      continue;
    }
    if (auto forOp = dyn_cast<scf::ForOp>(op)) {
      auto hiOp = forOp.getUpperBound().getDefiningOp<arith::ConstantIndexOp>();
      int64_t hi = hiOp ? hiOp.value() : 0;

      // Name the induction var
      std::string iname = "i";
      nameMap[forOp.getInductionVar()] = iname;

      writeIndent(os, indent);
      os << "for (@range(i32, " << hi << ")) |" << iname << "| {\n";

      // Pre-scan: mark which results have exactly one use (eligible for inlining).
      // A result is "inline-able" if it has exactly one use and the use is in
      // the same block (no multi-use temps needed).
      llvm::DenseSet<Value> inlineVals;
      for (auto &bodyOp : forOp.getBody()->getOperations()) {
        if (isa<memref::LoadOp>(bodyOp) || isa<arith::AddFOp>(bodyOp)) {
          if (bodyOp.getNumResults() == 1) {
            Value result = bodyOp.getResult(0);
            if (result.hasOneUse())
              inlineVals.insert(result);
          }
        }
      }

      // Track "inlined" expressions — values whose string expr is in nameMap but
      // no var statement was emitted.
      llvm::DenseSet<Value> inlinedExprs;

      // Emit loop body ops — walk the body block
      for (auto &bodyOp : forOp.getBody()->getOperations()) {
        if (isa<scf::YieldOp>(bodyOp)) continue;
        if (auto loadOp = dyn_cast<memref::LoadOp>(bodyOp)) {
          // Find the csl.var for the memref operand
          std::string bufName;
          if (auto varOp = dyn_cast_or_null<xilinx::csl::VarOp>(
                  loadOp.getMemref().getDefiningOp())) {
            bufName = varOp.getSymName().str();
          } else if (nameMap.count(loadOp.getMemref())) {
            bufName = nameMap[loadOp.getMemref()];
          } else {
            loadOp.emitOpError("KernelEmitter: memref.load operand not mapped");
            return failure();
          }
          std::string idxName;
          if (loadOp.getIndices().size() == 1) {
            Value idx = loadOp.getIndices()[0];
            if (nameMap.count(idx)) idxName = nameMap[idx];
            else idxName = "?";
          }
          std::string expr = bufName + "[" + idxName + "]";
          if (inlineVals.count(loadOp.getResult())) {
            // Inline: record expression, skip statement
            nameMap[loadOp.getResult()] = expr;
            inlinedExprs.insert(loadOp.getResult());
          } else {
            std::string tname = "t" + std::to_string(tempCount++);
            nameMap[loadOp.getResult()] = tname;
            writeIndent(os, indent + 1);
            os << "var " << tname << " = " << expr << ";\n";
          }
          continue;
        }
        if (auto addOp = dyn_cast<arith::AddFOp>(bodyOp)) {
          std::string lhs = nameMap.count(addOp.getLhs()) ? nameMap[addOp.getLhs()] : "?";
          std::string rhs = nameMap.count(addOp.getRhs()) ? nameMap[addOp.getRhs()] : "?";
          std::string expr = lhs + " + " + rhs;
          if (inlineVals.count(addOp.getResult())) {
            nameMap[addOp.getResult()] = expr;
            inlinedExprs.insert(addOp.getResult());
          } else {
            std::string tname = "t" + std::to_string(tempCount++);
            nameMap[addOp.getResult()] = tname;
            writeIndent(os, indent + 1);
            os << "var " << tname << " = " << expr << ";\n";
          }
          continue;
        }
        if (auto storeOp = dyn_cast<memref::StoreOp>(bodyOp)) {
          std::string bufName;
          if (auto varOp = dyn_cast_or_null<xilinx::csl::VarOp>(
                  storeOp.getMemref().getDefiningOp())) {
            bufName = varOp.getSymName().str();
          } else if (nameMap.count(storeOp.getMemref())) {
            bufName = nameMap[storeOp.getMemref()];
          } else {
            storeOp.emitOpError("KernelEmitter: memref.store memref operand not mapped");
            return failure();
          }
          std::string idxName;
          if (storeOp.getIndices().size() == 1) {
            Value idx = storeOp.getIndices()[0];
            if (nameMap.count(idx)) idxName = nameMap[idx];
            else idxName = "?";
          }
          std::string valName = nameMap.count(storeOp.getValue()) ?
              nameMap[storeOp.getValue()] : "?";
          writeIndent(os, indent + 1);
          os << bufName << "[" << idxName << "] = " << valName << ";\n";
          continue;
        }
        if (auto constOp2 = dyn_cast<arith::ConstantOp>(bodyOp)) {
          if (auto intAttr = dyn_cast<IntegerAttr>(constOp2.getValue()))
            nameMap[constOp2.getResult()] = std::to_string(intAttr.getInt());
          continue;
        }
        bodyOp.emitOpError(
            llvm::Twine("KernelEmitter: unsupported op in scf.for body: ") +
            bodyOp.getName().getStringRef());
        return failure();
      }

      writeIndent(os, indent);
      os << "}\n";
      continue;
    }
    if (auto loadOp = dyn_cast<memref::LoadOp>(op)) {
      std::string bufName;
      if (auto varOp = dyn_cast_or_null<xilinx::csl::VarOp>(
              loadOp.getMemref().getDefiningOp())) {
        bufName = varOp.getSymName().str();
      } else if (nameMap.count(loadOp.getMemref())) {
        bufName = nameMap[loadOp.getMemref()];
      } else {
        loadOp.emitOpError("KernelEmitter: memref.load operand not mapped");
        return failure();
      }
      std::string idxName;
      if (loadOp.getIndices().size() == 1) {
        Value idx = loadOp.getIndices()[0];
        if (nameMap.count(idx)) idxName = nameMap[idx];
        else idxName = "?";
      }
      std::string tname = "t" + std::to_string(tempCount++);
      nameMap[loadOp.getResult()] = tname;
      writeIndent(os, indent);
      os << "var " << tname << " = " << bufName << "[" << idxName << "];\n";
      continue;
    }
    if (auto addOp = dyn_cast<arith::AddFOp>(op)) {
      std::string lhs = nameMap.count(addOp.getLhs()) ? nameMap[addOp.getLhs()] : "?";
      std::string rhs = nameMap.count(addOp.getRhs()) ? nameMap[addOp.getRhs()] : "?";
      std::string tname = "t" + std::to_string(tempCount++);
      nameMap[addOp.getResult()] = tname;
      writeIndent(os, indent);
      os << "var " << tname << " = " << lhs << " + " << rhs << ";\n";
      continue;
    }
    if (auto storeOp = dyn_cast<memref::StoreOp>(op)) {
      std::string bufName;
      if (auto varOp = dyn_cast_or_null<xilinx::csl::VarOp>(
              storeOp.getMemref().getDefiningOp())) {
        bufName = varOp.getSymName().str();
      } else if (nameMap.count(storeOp.getMemref())) {
        bufName = nameMap[storeOp.getMemref()];
      } else {
        storeOp.emitOpError("KernelEmitter: memref.store memref operand not mapped");
        return failure();
      }
      std::string idxName;
      if (storeOp.getIndices().size() == 1) {
        Value idx = storeOp.getIndices()[0];
        if (nameMap.count(idx)) idxName = nameMap[idx];
        else idxName = "?";
      }
      std::string valName = nameMap.count(storeOp.getValue()) ?
          nameMap[storeOp.getValue()] : "?";
      writeIndent(os, indent);
      os << bufName << "[" << idxName << "] = " << valName << ";\n";
      continue;
    }
    op.emitOpError(
        llvm::Twine("KernelEmitter: unsupported op in csl.func body: ") +
        op.getName().getStringRef());
    return failure();
  }
  return success();
}

LogicalResult KernelEmitter::emitKernel(xilinx::csl::KernelOp kernelOp,
                                         llvm::raw_fd_ostream &os) {
  namespace cslns = xilinx::csl;

  os << "// Generated by air-translate --emit-csl-rt (KernelEmitter).\n\n";

  // 1. Header: always emitted.
  os << "param memcpy_params: comptime_struct;\n\n";
  os << "const sys_mod = @import_module(\"<memcpy/memcpy>\", memcpy_params);\n\n";

  // 2. Collect csl.var ops and determine N (common dim).
  struct VarInfo {
    std::string symName;
    std::string eltType;
    int64_t dim;
    mlir::Value ssaVal;
  };
  llvm::SmallVector<VarInfo, 4> vars;
  bool dimOk = true;

  for (auto &op : kernelOp.getBody().getOps()) {
    if (auto varOp = dyn_cast<cslns::VarOp>(&op)) {
      auto memTy = dyn_cast<MemRefType>(varOp.getResult().getType());
      if (!memTy || memTy.getRank() != 1) {
        varOp.emitOpError("KernelEmitter: csl.var must have 1-D memref type");
        return failure();
      }
      bool typeOk = true;
      std::string eltName = cslEltType(memTy.getElementType(), varOp, typeOk).str();
      if (!typeOk) return failure();
      int64_t dim = memTy.getDimSize(0);
      vars.push_back({varOp.getSymName().str(), eltName, dim, varOp.getResult()});
    }
  }

  // Check if all vars share the same dim.
  int64_t commonDim = vars.empty() ? -1 : vars[0].dim;
  for (auto &v : vars) {
    if (v.dim != commonDim) { dimOk = false; break; }
  }
  bool useN = dimOk && !vars.empty() && commonDim > 0;
  if (useN)
    os << "const N: i32 = " << commonDim << ";\n\n";

  // 3. Var declarations.
  for (auto &v : vars) {
    std::string sizeStr = useN ? "N" : std::to_string(v.dim);
    os << "var " << v.symName << ": [" << sizeStr << "]" << v.eltType << ";\n";
  }
  if (!vars.empty()) os << "\n";

  // 4. Collect csl.export_symbol ops: sym -> alias (or empty if no alias).
  // Also categorise: var-with-alias -> pointer alias, func-no-alias -> function export.
  struct ExportInfo {
    std::string symName;
    std::string alias;  // empty if no alias attribute
  };
  llvm::SmallVector<ExportInfo, 8> exports;
  for (auto &op : kernelOp.getBody().getOps()) {
    if (auto expSym = dyn_cast<cslns::ExportSymbolOp>(&op)) {
      std::string sym = expSym.getSymbol().str();
      std::string al = expSym.getAlias().value_or("").str();
      exports.push_back({sym, al});
    }
  }

  // Build a set of var sym_names for lookup.
  std::set<std::string> varSymNames;
  for (auto &v : vars) varSymNames.insert(v.symName);

  // 4. Pointer aliases.
  // For each export with an alias, and whose sym is a var: emit pointer alias.
  // Direction comes from hostExportDir[alias].
  bool hasPtrs = false;
  for (auto &exp : exports) {
    if (exp.alias.empty()) continue; // no alias => function export
    if (!varSymNames.count(exp.symName)) continue; // not a var

    // Find var info
    std::string eltType;
    for (auto &v : vars) {
      if (v.symName == exp.symName) { eltType = v.eltType; break; }
    }
    // Look up direction from host-level csl.export_name with name == alias
    auto it = hostExportDir.find(exp.alias);
    bool isIn = (it != hostExportDir.end() && it->second == "in");

    std::string qualifier = isIn ? "var" : "const";
    // Pointer name is derived from the alias (e.g. alias "a" -> a_ptr)
    os << qualifier << " " << exp.alias << "_ptr: [*]" << eltType
       << " = &" << exp.symName << ";\n";
    hasPtrs = true;
  }
  if (hasPtrs) os << "\n";

  // 5. Function definitions.
  // Collect function-typed exports (no alias) to know which funcs get unblock_cmd_stream.
  std::set<std::string> funcExports;
  for (auto &exp : exports) {
    if (exp.alias.empty() && !varSymNames.count(exp.symName))
      funcExports.insert(exp.symName);
    // Also check host-level export_name to determine if it's function-typed
  }
  // Any func whose name appears as a function-type host export.
  std::set<std::string> hostFuncExports;
  for (auto &kv : hostExportDir) {
    if (kv.second.empty()) // empty direction means function type
      hostFuncExports.insert(kv.first);
  }

  for (auto &op : kernelOp.getBody().getOps()) {
    if (auto funcOp = dyn_cast<cslns::FuncOp>(&op)) {
      StringRef fname = funcOp.getSymName();
      os << "fn " << fname << "() void {\n";

      // Build name map: pre-populate csl.var SSA results
      llvm::DenseMap<mlir::Value, std::string> nameMap;
      for (auto &kop : kernelOp.getBody().getOps()) {
        if (auto varOp = dyn_cast<cslns::VarOp>(&kop))
          nameMap[varOp.getResult()] = varOp.getSymName().str();
      }
      unsigned tempCount = 0;

      if (failed(emitFuncBody(funcOp, os, nameMap, tempCount, /*indent=*/1)))
        return failure();

      // Append unblock_cmd_stream if this func is a function-typed host export
      if (hostFuncExports.count(fname.str()))
        os << "  sys_mod.unblock_cmd_stream();\n";

      os << "}\n\n";
    }
  }

  // 6. Comptime block.
  os << "comptime {\n";
  for (auto &exp : exports) {
    if (!exp.alias.empty() && varSymNames.count(exp.symName)) {
      // Pointer alias export: use alias_ptr name
      os << "  @export_symbol(" << exp.alias << "_ptr, \"" << exp.alias << "\");\n";
    } else if (exp.alias.empty()) {
      // Function export (no alias)
      os << "  @export_symbol(" << exp.symName << ");\n";
    }
  }
  os << "}\n";

  return success();
}

/// Simple Python code generation utility
class PythonWriter {
public:
  explicit PythonWriter(llvm::raw_ostream &os) : os(os), indentLevel(0) {}

  void indent() { indentLevel++; }
  void dedent() {
    if (indentLevel > 0)
      indentLevel--;
  }

  llvm::raw_ostream &line() {
    os << std::string(indentLevel * 4, ' ');
    return os;
  }

  void blankLine() { os << "\n"; }
  llvm::raw_ostream &raw() { return os; }

private:
  llvm::raw_ostream &os;
  int indentLevel;
};

/// Extracts and emits CSL kernel bodies and generates Python runtime.
class CSLRuntimeToPyTranslator {
public:
  CSLRuntimeToPyTranslator(llvm::raw_ostream &out) : out(out), writer(out) {}

  LogicalResult translate(ModuleOp module) {
    // Step 0: Emit layout.csl via LayoutEmitter (Phase 4)
    LayoutEmitter layoutEmitter(cslOutputDir);
    if (failed(layoutEmitter.emit(module)))
      return failure();

    // Step 1: Emit PE program .csl files via KernelEmitter (Phase 5)
    KernelEmitter kernelEmitter(cslOutputDir, module);
    if (failed(kernelEmitter.emit()))
      return failure();

    // Step 2: Generate single run.py file with inline build_layout()
    emitRunPy(module);

    return mlir::success();
  }

private:
  llvm::raw_ostream &out;
  PythonWriter writer;

  void emitRunPy(ModuleOp module) {
    out << "# ============================================================================\n";
    out << "# run.py - Complete Host Runtime Program\n";
    out << "# ============================================================================\n";
    out << "\n";

    out << "#!/usr/bin/env cs_python\n";
    out << "\"\"\"Auto-generated run.py using SdkLayout and SdkRuntime API.\"\"\"\n";
    out << "\n";

    out << "import argparse\n";
    out << "import numpy as np\n";
    out << "# sdkruntimepybind: SdkRuntime API + SdkLayout API\n";
    out << "from cerebras.sdk.runtime.sdkruntimepybind import (\n";
    out << "    SdkRuntime, SdkTarget, SdkLayout, SimfabConfig, get_platform,\n";
    out << ")\n";
    out << "\n";

    // Emit build_layout function
    out << "def build_layout(platform):\n";
    out << "    \"\"\"\n";
    out << "    Build and compile the layout for the WSE.\n";
    out << "    \n";
    out << "    Args:\n";
    out << "        platform: SdkRuntime platform object\n";
    out << "    \n";
    out << "    Returns:\n";
    out << "        compile_artifacts: Result of layout.compile(out_prefix='out')\n";
    out << "    \"\"\"\n";
    out << "    # Create layout\n";
    out << "    layout = SdkLayout(platform)\n";
    out << "\n";

    // Collect and emit all csl_rt operations in order
    emitLayoutOperations(module);

    out << "    # Compile layout\n";
    out << "    compile_artifacts = layout.compile(out_prefix='out')\n";
    out << "    return compile_artifacts\n";
    out << "\n";
    out << "\n";

    // Emit main function
    out << "def main():\n";
    out << "    # Parse command-line arguments\n";
    out << "    parser = argparse.ArgumentParser(description='Run WSE kernel')\n";
    out << "    parser.add_argument('--cmaddr', type=str, default=None,\n";
    out << "                        help='IP:port for CS system')\n";
    out << "    parser.add_argument('--arch', type=str, choices=['wse2', 'wse3'],\n";
    out << "                        default='wse3', help='Target WSE architecture')\n";
    out << "    args = parser.parse_args()\n";
    out << "\n";

    out << "    # Setup platform\n";
    out << "    config = SimfabConfig(dump_core=True)\n";
    out << "    target = SdkTarget.WSE3 if args.arch == 'wse3' else SdkTarget.WSE2\n";
    out << "    platform = get_platform(args.cmaddr, config, target)\n";
    out << "\n";

    out << "    # Build and compile layout\n";
    out << "    compile_artifacts = build_layout(platform)\n";
    out << "\n";

    out << "    # Create and run runtime\n";
    out << "    runtime = SdkRuntime(compile_artifacts, platform, memcpy_required=False)\n";
    out << "\n";

    // Emit runtime operations
    emitRuntimeOperations(module);

    out << "\n";
    out << "    print('SUCCESS!')\n";
    out << "\n";
    out << "\n";
    out << "if __name__ == '__main__':\n";
    out << "    main()\n";
  }

  void emitLayoutOperations(ModuleOp module) {
    // Process operations at module level and inside functions
    emitLayoutOpsInFunction(module.getOperation());

    // Also walk through any func.func operations
    module.walk([&](func::FuncOp func) {
      emitLayoutOpsInFunction(func.getOperation());
    });
  }

  void emitLayoutOpsInFunction(Operation *op) {
    // Process direct children in order (preserves sequence)
    for (auto &region : op->getRegions()) {
      for (auto &block : region.getBlocks()) {
        for (auto &opChild : block.getOperations()) {
          auto opName = opChild.getName().getStringRef();

          if (opName == "csl_rt.create_code_region") {
            auto createCodeRegion = dyn_cast<CreateCodeRegionOp>(&opChild);
            if (createCodeRegion) {
              StringRef source = createCodeRegion.getSourceAttr().getValue();
              StringRef name = createCodeRegion.getNameAttr().getValue();
              int64_t width = createCodeRegion.getWidthAttr().getValue().getSExtValue();
              int64_t height =
                  createCodeRegion.getHeightAttr().getValue().getSExtValue();

              out << "    code_region = layout.create_code_region(\"" << source
                  << "\", \"" << name << "\", " << width << ", " << height << ")\n";
            }
          } else if (opName == "csl_rt.place") {
            auto place = dyn_cast<PlaceOp>(&opChild);
            if (place) {
              int64_t x = place.getXAttr().getValue().getSExtValue();
              int64_t y = place.getYAttr().getValue().getSExtValue();
              out << "    code_region.place(" << x << ", " << y << ")\n";
            }
          } else if (opName == "csl_rt.set_param_all") {
            auto setParam = dyn_cast<SetParamAllOp>(&opChild);
            if (setParam) {
              StringRef paramName = setParam.getParamNameAttr().getValue();
              int64_t paramValue = setParam.getParamValueAttr().getValue().getSExtValue();
              out << "    code_region.set_param_all(\"" << paramName << "\", "
                  << paramValue << ")\n";
            }
          } else if (opName == "csl_rt.export_name") {
            auto exportName = dyn_cast<ExportNameOp>(&opChild);
            if (exportName) {
              StringRef symName = exportName.getSymbolNameAttr().getValue();
              StringRef symType = exportName.getSymbolTypeAttr().getValue();
              out << "    layout.export_name(\"" << symName << "\", \"" << symType
                  << "\")\n";
            }
          }
        }
      }
    }
  }

  void emitRuntimeOperations(ModuleOp module) {
    // Process operations at module level and inside functions
    emitRuntimeOpsInFunction(module.getOperation());

    // Also walk through any func.func operations
    module.walk([&](func::FuncOp func) {
      emitRuntimeOpsInFunction(func.getOperation());
    });
  }

  void emitRuntimeOpsInFunction(Operation *op) {
    out << "    try:\n";
    out << "        # Load and run the program\n";
    out << "        runtime.load()\n";
    out << "\n";

    // Process direct children in order (preserves sequence)
    bool foundH2D = false;
    bool foundLaunch = false;
    bool foundD2H = false;

    for (auto &region : op->getRegions()) {
      for (auto &block : region.getBlocks()) {
        for (auto &opChild : block.getOperations()) {
          auto opName = opChild.getName().getStringRef();

          if (opName == "csl_rt.load") {
            // Already emitted above
          } else if (opName == "csl_rt.get_id") {
            auto getId = dyn_cast<GetIdOp>(&opChild);
            if (getId) {
              StringRef symbolName = getId.getSymbolNameAttr().getValue();
              out << "        id_" << symbolName << " = runtime.get_id(\""
                  << symbolName << "\")\n";
            }
          } else if (opName == "csl_rt.memcpy_h2d") {
            if (!foundH2D) {
              out << "\n";
              out << "        # Host-to-device transfers\n";
              foundH2D = true;
            }
            auto memcpyH2D = dyn_cast<MemcpyH2dOp>(&opChild);
            if (memcpyH2D) {
              int32_t destId = memcpyH2D.getDestIdAttr().getInt();
              StringRef srcName = memcpyH2D.getSrcNameAttr().getValue();
              int64_t px = memcpyH2D.getPxAttr().getValue().getSExtValue();
              int64_t py = memcpyH2D.getPyAttr().getValue().getSExtValue();
              int64_t w = memcpyH2D.getWAttr().getValue().getSExtValue();
              int64_t h = memcpyH2D.getHAttr().getValue().getSExtValue();
              int64_t elemPerPe =
                  memcpyH2D.getElemPerPeAttr().getValue().getSExtValue();

              out << "        runtime.memcpy_h2d(" << destId << ", \"" << srcName
                  << "\", " << px << ", " << py << ", " << w << ", " << h << ", "
                  << elemPerPe << ")\n";
            }
          } else if (opName == "csl_rt.launch") {
            if (!foundLaunch) {
              out << "\n";
              out << "        # Launch compute kernel\n";
              foundLaunch = true;
            }
            auto launch = dyn_cast<LaunchOp>(&opChild);
            if (launch) {
              StringRef symbolName = launch.getSymbolNameAttr().getValue();
              out << "        runtime.launch(\"" << symbolName << "\")\n";
            }
          } else if (opName == "csl_rt.memcpy_d2h") {
            if (!foundD2H) {
              out << "\n";
              out << "        # Device-to-host transfers\n";
              foundD2H = true;
            }
            auto memcpyD2H = dyn_cast<MemcpyD2hOp>(&opChild);
            if (memcpyD2H) {
              StringRef destName = memcpyD2H.getDestNameAttr().getValue();
              int64_t px = memcpyD2H.getPxAttr().getValue().getSExtValue();
              int64_t py = memcpyD2H.getPyAttr().getValue().getSExtValue();
              int64_t w = memcpyD2H.getWAttr().getValue().getSExtValue();
              int64_t h = memcpyD2H.getHAttr().getValue().getSExtValue();
              int64_t elemPerPe =
                  memcpyD2H.getElemPerPeAttr().getValue().getSExtValue();

              out << "        runtime.memcpy_d2h(\"" << destName << "\", " << px
                  << ", " << py << ", " << w << ", " << h << ", " << elemPerPe
                  << ")\n";
            }
          }
        }
      }
    }

    out << "\n";
    out << "    finally:\n";
    out << "        # Stop the program\n";
    out << "        runtime.stop()\n";
  }
};

/// Translation function for csl_rt → Python.
static LogicalResult translateCSLRuntimeToPy(ModuleOp module, llvm::raw_ostream &os) {
  CSLRuntimeToPyTranslator translator(os);
  return translator.translate(module);
}

} // namespace

void xilinx::csl_rt::registerCSLRuntimeToPyTranslation() {
  TranslateFromMLIRRegistration registration(
      "emit-csl-rt", "Emit CSL Runtime to Python",
      [](ModuleOp module, llvm::raw_ostream &os) {
        return translateCSLRuntimeToPy(module, os);
      },
      [](DialectRegistry &registry) {
        registry.insert<xilinx::csl::CSLDialect, xilinx::csl_rt::CSLRuntimeDialect,
                        mlir::func::FuncDialect, mlir::arith::ArithDialect,
                        mlir::memref::MemRefDialect, mlir::scf::SCFDialect>();
      });
}
