#!/usr/bin/env cs_python
# Generated by air-translate --emit-csl-host
#
# Run against a pre-compiled artifact directory produced by
#   cslc layout.csl --arch=wseN ... -o <dir> --memcpy --channels 1
# The companion commands_wse{2,3}.sh scripts do both steps.

import argparse
import sys
import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import (
    SdkRuntime,
    MemcpyOrder,
    MemcpyDataType,
)

parser = argparse.ArgumentParser()
parser.add_argument('--name', default='compiled',
                    help='compiled artifact directory (default: compiled)')
parser.add_argument('--cmaddr', default=None,
                    help='IP:port for CS system (default: simulator)')
args = parser.parse_args()

N = 128

# Host buffers.
arg0 = np.arange(N, dtype=np.float32)
arg1 = np.zeros(N, dtype=np.float32)

# Create runtime and load compiled artifacts.
runner = SdkRuntime(args.name, cmaddr=args.cmaddr, simfab_numthreads=32)
runner.load()
runner.run()

# Host-to-device copies (inputs).
runner.memcpy_h2d(runner.get_id("x"), arg0, 0, 0, 1, 1, 128,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)

# Launch compute kernel.
runner.launch("compute", nonblock=False)

# Device-to-host copies (outputs).
runner.memcpy_d2h(arg1, runner.get_id("y"), 0, 0, 1, 1, 128,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)

runner.stop()

# Reference computation (numpy, interpreted from csl.func @compute body).
_x_ref = arg0[:128].astype(np.float32).copy()
_y_ref = np.zeros(128, dtype=np.float32)
t3 = np.float32(2)
for i4 in range(0, 128, 1):
    t5 = _x_ref[i4]
    t6 = t5 / t3
    _y_ref[i4] = t6

# Verification: compare each D2H output against its reference.
_mismatch = False
_expected_arg1 = np.zeros_like(arg1)
_expected_arg1[:128] = _y_ref
if not np.allclose(arg1, _expected_arg1, atol=1e-5, rtol=1e-5):
    print("MISMATCH in arg1 (var @y):", file=sys.stderr)
    print(f"  expected[:8] = {_expected_arg1[:min(8, len(_expected_arg1))]}", file=sys.stderr)
    print(f"  got[:8]      = {arg1[:min(8, len(arg1))]}", file=sys.stderr)
    _mismatch = True
else:
    print(f"  arg1[:8] = {arg1[:min(8, len(arg1))]} (matches reference)")
if _mismatch:
    sys.exit(1)
print("SUCCESS!")
