#!/usr/bin/env cs_python
# Generated by air-translate --emit-csl-host
#
# Run against a pre-compiled artifact directory produced by
#   cslc layout.csl --arch=wseN ... -o <dir> --memcpy --channels 1
# The companion commands_wse{2,3}.sh scripts do both steps.

import argparse
import sys
import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import (
    SdkRuntime,
    MemcpyOrder,
    MemcpyDataType,
)

parser = argparse.ArgumentParser()
parser.add_argument('--name', default='compiled',
                    help='compiled artifact directory (default: compiled)')
parser.add_argument('--cmaddr', default=None,
                    help='IP:port for CS system (default: simulator)')
args = parser.parse_args()

N = 128

# Host buffers.
arg0 = np.arange(N, dtype=np.float32)
arg1 = np.zeros(N, dtype=np.float32)

# Create runtime and load compiled artifacts.
runner = SdkRuntime(args.name, cmaddr=args.cmaddr, simfab_numthreads=32)
runner.load()
runner.run()

# Host-to-device copies (inputs).
runner.memcpy_h2d(runner.get_id("x"), arg0, 0, 0, 1, 1, 128,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)
runner.memcpy_h2d(runner.get_id("y"), arg1, 0, 0, 1, 1, 128,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)

# Launch compute kernel.
runner.launch("compute", nonblock=False)

# Device-to-host copies (outputs).
runner.memcpy_d2h(arg1, runner.get_id("y"), 0, 0, 1, 1, 128,
                  streaming=False,
                  order=MemcpyOrder.ROW_MAJOR,
                  data_type=MemcpyDataType.MEMCPY_32BIT,
                  nonblock=False)

runner.stop()

# Reference-compute skipped: unsupported op: csl.get_mem_dsd
# Output sanity checks (no reference model available).
def _sanity(name, buf):
    head = buf[:min(8, len(buf))]
    print(f"  {name}[:{len(head)}] = {list(head)}")
    return bool(np.any(buf != 0))

print("Output buffers:")
any_nonzero = False
any_nonzero = _sanity("arg1", arg1) or any_nonzero
# Note: all-zero output is OK if the kernel has no stores (e.g. empty compute).
print("SUCCESS!")
