#!/usr/bin/env cs_python
# Generated by air-translate --emit-csl-host
#
# Run against a pre-compiled artifact directory produced by
#   cslc layout.csl --arch=wseN ... -o <dir> --memcpy --channels 1
# The companion commands_wse{2,3}.sh scripts do both steps.

import argparse
import sys
import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import (
    SdkRuntime,
    MemcpyOrder,
    MemcpyDataType,
)

parser = argparse.ArgumentParser()
parser.add_argument('--name', default='compiled',
                    help='compiled artifact directory (default: compiled)')
parser.add_argument('--cmaddr', default=None,
                    help='IP:port for CS system (default: simulator)')
args = parser.parse_args()

N = 256

# Host buffers.

# Create runtime and load compiled artifacts.
runner = SdkRuntime(args.name, cmaddr=args.cmaddr, simfab_numthreads=32)
runner.load()
runner.run()

# Host-to-device copies (inputs).

# Launch compute kernel.
runner.launch("compute", nonblock=False)

# Device-to-host copies (outputs).

runner.stop()

# Output sanity checks (no reference model available).
print("SUCCESS!")
